(function(){
'use strict';
const CSS=document.createElement('style');CSS.textContent=`
.rc7-card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:14px;margin-bottom:12px}.rc7-hero{background:linear-gradient(135deg,var(--navy),#174a68);color:#fff;border-radius:15px;padding:16px;margin-bottom:12px}.rc7-hero h2{margin:5px 0 7px;font-size:20px}.rc7-hero p{margin:0;color:#d8e8e8;font-size:13px;line-height:1.5}.rc7-k{display:inline-block;background:#edf7f6;color:var(--teal);border-radius:999px;padding:5px 9px;font-size:10px;font-weight:900;text-transform:uppercase}.rc7-info{background:#eef7f6;border-left:5px solid var(--teal);border-radius:11px;padding:11px 12px;margin:10px 0;font-size:13px;line-height:1.5}.rc7-q{font-size:17px;font-weight:900;color:var(--navy);line-height:1.35;margin:12px 0}.rc7-opt{display:block;width:100%;text-align:left;border:1.5px solid var(--line);border-radius:11px;padding:12px;margin:8px 0;background:#fff;color:var(--ink);font-size:13px;font-weight:650}.rc7-opt.good{background:var(--greenbg);border-color:var(--green);color:var(--green)}.rc7-opt.bad{background:var(--redbg);border-color:var(--red);color:var(--red)}.rc7-opt.dim{opacity:.55}.rc7-fb{border-radius:11px;padding:12px;margin:10px 0;font-size:13px;line-height:1.5}.rc7-fb.good{background:var(--greenbg);color:var(--green)}.rc7-fb.try{background:var(--amberbg);color:var(--amber)}.rc7-expbtn{width:100%;border:1.5px solid var(--teal);background:#f7fbfb;color:var(--navy);border-radius:11px;padding:11px 12px;font-weight:900;text-align:left;margin:8px 0}.rc7-exp{display:none;border:1px solid var(--line);border-radius:11px;background:#fff;padding:12px;margin:0 0 10px;font-size:12.8px;line-height:1.5}.rc7-exp.open{display:block}.rc7-next{width:100%;border:0;border-radius:11px;background:var(--navy);color:#fff;padding:13px;font-weight:900;margin-top:8px}.rc7-progress{display:flex;gap:3px;margin:10px 0 12px}.rc7-progress span{height:6px;flex:1;border-radius:5px;background:#dde8e8}.rc7-progress .done{background:var(--teal)}.rc7-progress .now{background:var(--navy)}.rc7-image{border:2px dashed #9eb8b7;border-radius:12px;background:#fbfdfd;color:#587176;padding:15px;margin:10px 0;text-align:center;font-size:12px;line-height:1.45}@media(max-width:620px){.rc7-q{font-size:16px}.rc7-opt{font-size:12.7px;padding:11px}}
`;document.head.appendChild(CSS);
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function parseCases(){try{return String(raw||'').trim().split(/\n+/).map(line=>{const p=line.split('|');return{id:+p[0],title:p[1],cat:p[2],level:p[3],presentation:p[4],exam:p[5],tests:p[6],image:p[7],diff:p[8],interpret:p[9],management:p[10],monitor:p[11],module:p[12]}}).filter(c=>c.id&&c.title)}catch(e){console.error(e);return[]}}
const CASES=parseCases();let ST={c:null,blind:false,i:0,score:0,answers:[]};
const HIST={ia:'Ask about duration and morning stiffness, exact joint distribution, psoriasis/nail disease, dactylitis/enthesitis, uveitis, IBD, recent GI/GU infection and family history.',crystal:'Clarify speed of onset, prior attacks, fever/rigors, skin breach/prosthesis, recent procedures, CKD/diuretics, alcohol/diet and infection risks.',ctd:'Ask about photosensitivity, oral/nasal ulcers, Raynaud phenomenon, sicca, serositis, thrombosis/pregnancy history and renal/pulmonary/neurologic symptoms.',vasc:'Ask about visual symptoms, jaw claudication, ENT disease, haemoptysis/dyspnoea, haematuria, neuropathy, purpura, ischaemia and constitutional symptoms.',myo:'Clarify true proximal weakness, dysphagia, dyspnoea, rash, Raynaud, drug/toxin exposure and malignancy clues.',pain:'Clarify mechanical versus inflammatory timing, stiffness duration, activity relationship, sleep, fatigue, focal neurology and inflammatory red flags.',systemic:'Clarify chronology, fever/weight loss, organ involvement, infection exposure, medication history and malignancy clues.'};
const EXAM={ia:'Perform a full joint count and examine skin/scalp/nails, entheses, dactylitis, spine/SI joints and relevant extra-articular systems.',crystal:'Examine the affected joint for effusion/warmth and look for tophi, infection source, other involved joints and systemic sepsis features.',ctd:'Examine skin, mucosa, hands/nails, glands, joints, cardiopulmonary system, neurology and signs of renal/vascular involvement.',vasc:'Check pulses/BP symmetry, temporal arteries where relevant, skin, ENT, chest, peripheral nerves, eyes and digital perfusion.',myo:'Document proximal/distal power, neck flexion, swallowing/respiratory status, rash, joints and lung findings.',pain:'Localise pain anatomically; assess range of motion, focal tenderness, provocative manoeuvres, neurology, objective synovitis and widespread tenderness.',systemic:'Perform a general and system examination targeted to the history.'};
function poc(c){if(c.cat==='crystal')return'Perform arthrocentesis of the hot swollen joint for cell count, crystals, Gram stain and culture.';if(c.cat==='vasc'||c.cat==='ctd')return'Perform bedside urinalysis for blood/protein, check BP and oxygen saturation, and assess relevant organ signs.';if(c.cat==='myo')return'Formally grade muscle power and assess swallowing, respiratory status and oxygen saturation.';if(c.cat==='ia')return'Document swollen/tender joint count and enthesitis/dactylitis; aspirate an unexplained large effusion if infection/crystal disease remains possible.';return'Use focused bedside tests only when they answer a specific safety or diagnostic question.'}
function blood(c){if(c.cat==='ia')return'FBC, renal/liver profile, ESR/CRP and targeted RF/anti-CCP when RA is plausible; avoid indiscriminate autoantibody panels.';if(c.cat==='crystal')return'FBC, renal profile, CRP/ESR and serum urate in context; obtain blood cultures if febrile or systemically unwell.';if(c.cat==='ctd')return'FBC, renal/liver profile, ESR/CRP, urine protein assessment and phenotype-directed ANA/ENA, dsDNA/complement or APS testing.';if(c.cat==='vasc')return'FBC, renal/liver profile, ESR/CRP, urine protein assessment and mechanism-directed ANCA/PR3/MPO, complement, cryoglobulins or infection tests.';if(c.cat==='myo')return'CK/aldolase, AST/ALT/LDH, FBC, renal profile, inflammatory markers and phenotype-directed myositis antibodies.';return'Order focused baseline bloods only where the presentation suggests inflammatory/systemic disease or where treatment safety requires them.'}
function xray(c){const t=(c.title+' '+c.image).toLowerCase();if(/axial|spondylo|sacroili/.test(t))return'Obtain a plain pelvic/SI radiograph when chronic structural axial disease is suspected, recognising early disease may be normal.';if(/rheumatoid|psoriatic|hand|cppd|haemochrom/.test(t))return'Obtain plain radiographs of symptomatic hands/feet or involved joints to assess erosions, joint-space loss, new bone formation or chondrocalcinosis.';if(/gout|knee|septic/.test(t))return'Use plain radiography for structural context, but do not let it delay aspiration of a hot joint.';return'Use plain radiography only when structural bone/joint disease is relevant to the differential.'}
function xrayResult(c){const t=(c.title+' '+c.tests+' '+c.image).toLowerCase();if(/non-radiographic/.test(t))return'Plain pelvic radiography is normal/non-diagnostic; early inflammatory axial disease remains possible.';if(/sacroili|axial/.test(t))return'Plain films show sacroiliac structural changes compatible with chronic sacroiliitis.';if(/rheumatoid/.test(t))return'Radiographs may be normal early; established disease may show marginal erosions and joint-space loss.';if(/cppd|chondrocalc/.test(t))return'Radiographs demonstrate chondrocalcinosis/CPPD-pattern structural change where present.';if(/osteoarthritis|\boa\b/.test(t))return'Radiographs demonstrate degenerative joint-space loss and osteophyte formation in the symptomatic distribution.';return'Plain radiographs provide structural context but are not diagnostic by themselves.'}
function advanced(c){const s=String(c.image||'').replace(/^INSERT IMAGE HERE\s*[—-]?\s*/i,'').replace(/\.$/,'');if(s)return s; if(c.cat==='ia')return'Musculoskeletal ultrasound for synovitis/enthesitis or MRI for early axial disease if uncertainty remains.';if(c.cat==='vasc')return'Targeted vascular/chest imaging and tissue biopsy according to vessel size and organ involvement.';if(c.cat==='myo')return'Muscle MRI and HRCT/PFTs when ILD is suspected; biopsy if needed to resolve uncertainty.';return'Choose a targeted second-line study only if it will change the differential or management.'}
function options(correct,alts){return shuffle([correct,...alts.filter(Boolean).filter(x=>x!==correct).slice(0,3)])}
function q(stage,reveal,question,correct,alts,why,image){return{stage,reveal,question,correct,opts:options(correct,alts),why,image}}
function steps(c){const h=HIST[c.cat]||HIST.systemic,e=EXAM[c.cat]||EXAM.systemic;const diffs=(c.diff||'').split(';').map(x=>x.trim()).filter(Boolean);return[
q('Presentation','The patient presents with: '+c.presentation,'What additional history would you ask next?',h,['Ask only about pain score and analgesia use','Order autoimmune serology before clarifying the history','Wait for imaging before asking about associated-system symptoms'],'The preferred history targets features that materially change the differential before tests are ordered.'),
q('History','You obtain the additional history and now need to examine the patient.','Which examination approach is most appropriate?',e,['Examine only the single most painful joint','Use inflammatory markers instead of examination','Look only for tender points'],'The examination should test the suspected syndrome and look for features that support or contradict competing diagnoses.'),
q('Examination','Examination shows: '+c.exam,'Which additional signs would you actively look for?',e,['No further examination is needed once synovitis is seen','Only repeat the same painful-joint examination','Skip examination and proceed directly to MRI'],'Additional signs can distinguish disease families and identify organ-threatening complications.'),
q('Differential','You now have the presenting history plus focused examination findings.','Which differential is most appropriate at this point?',c.diff||'Keep inflammatory, infectious, crystal and mechanical mimics active.',[diffs[0]||'Mechanical pain only','A single diagnosis only with no competing mimic','No differential is needed until all tests return'],'A short, clinically plausible differential protects against premature closure.'),
q('Point-of-care','Before sending broad investigations, you consider immediate bedside tests.','What point-of-care or bedside assessment is most useful now?',poc(c),['Skip bedside testing and order every rheumatology antibody','Request whole-body CT first','Use treatment response as a diagnostic test'],'Bedside tests should address immediate safety or a high-yield diagnostic discriminator.'),
q('Point-of-care result','The bedside assessment is completed. '+(c.cat==='crystal'?'Joint fluid is inflammatory and has been sent for crystals, Gram stain and culture.':c.cat==='vasc'||c.cat==='ctd'?'Urinalysis/BP/oxygen saturation are available for interpretation.':c.cat==='myo'?'Objective muscle weakness has been documented and bulbar/respiratory involvement assessed.':'The distribution of objective inflammation has been documented.'),'What is the best next step?',blood(c),['Repeat the bedside test indefinitely before any bloods','Order every autoantibody regardless of phenotype','Stop the work-up because bedside testing is sufficient'],'Blood tests should now be targeted to the phenotype and treatment/safety questions.'),
q('Blood tests','Blood results return: '+c.tests,'How should you interpret these blood results?',c.interpret,['One abnormal blood test establishes the diagnosis regardless of phenotype','Normal inflammatory markers exclude inflammatory rheumatic disease','Ignore discordance between blood results and the examination'],'Laboratory results modify probability and should be integrated with the clinical pattern.'),
q('Plain radiology','You now decide whether structural imaging adds useful information.','Which plain radiograph strategy is most appropriate?',xray(c),['Request MRI before considering whether a plain film answers the structural question','Avoid any structural imaging even when bone/joint damage is central','Use a normal radiograph to exclude all inflammatory rheumatic disease'],'Plain radiographs are useful for structural disease, but their role depends on the clinical question.'),
q('X-ray result','The plain radiograph is reviewed: '+xrayResult(c),'What does this result mean for the differential?', 'Use the radiograph to re-rank the differential, recognising that structural imaging may support but rarely proves the diagnosis alone.',['The radiograph alone establishes the diagnosis','A normal radiograph excludes all inflammatory disease','Ignore the radiograph because only MRI matters'],'Interpret imaging in context; normal early films do not exclude inflammatory disease.'),
q('Advanced imaging / pathology','The case remains unresolved enough to justify a more targeted study.','What advanced test would you choose next?',advanced(c),['Order CT, MRI, ultrasound and PET all at once','Repeat the same plain film immediately','Start definitive long-term therapy before resolving the key uncertainty'],'Second-line imaging or biopsy should answer the key remaining discriminator.',c.image),
q('Advanced result','The targeted study/pathology result becomes available.','How should you interpret this result?',c.interpret,['Name the diagnosis from the image alone without considering the history','Treat any imaging abnormality as disease-specific','Ignore contradictory clinical features'],'Describe the objective pattern first, then integrate it with the whole case.'),
q('Refined differential','You now have history, examination, bedside testing, bloods and imaging.','Which diagnosis is now most likely?',c.title,[...diffs,'Infectious mimic','Mechanical / degenerative mimic'],'This is the point to commit after the evidence has accumulated progressively.'),
q('Treatment','The working diagnosis is now '+c.title+'.','Which treatment direction is most appropriate?',c.management,['Start long-term immunosuppression before excluding important infection','Treat only the laboratory abnormality','Delay all treatment until every conceivable test has been performed'],'Treatment should reflect disease severity, dominant domain, organ involvement and safety.'),
q('Treatment safety','Before finalising therapy, what safety step is most important?','Review infection risk, baseline organ/laboratory status, vaccination needs, pregnancy potential where relevant, interactions and treatment-specific contraindications.',['No baseline safety assessment is needed','Repeat broad autoantibody panels instead of safety screening','Treatment safety can wait until toxicity develops'],'Safe treatment requires patient-specific baseline assessment.'),
q('Monitoring','Treatment has started. How should follow-up be structured?',c.monitor,['Monitor symptoms only and ignore objective activity/toxicity','Stop follow-up once symptoms improve','Use repeated autoantibody panels as the main response measure'],'Monitoring should assess both effectiveness and harm using disease-appropriate objective measures.'),
q('Reassessment','The patient does not improve as expected. What should you do?','Reassess diagnosis, adherence, treatment adequacy, complications and important mimics; escalate urgently if organ-threatening features develop.',['Simply increase treatment without reconsidering the diagnosis','Assume non-response confirms the original diagnosis','Ignore new red flags until the next routine visit'],'Non-response is a reason to reconsider the case, not just intensify treatment.')
]}
function show(id){['home','player','summary','about'].forEach(x=>document.getElementById(x)?.classList.toggle('hidden',x!==id));window.scrollTo(0,0)}
function start(c,blind){ST={c,blind:!!blind,i:0,score:0,answers:[]};show('player');render()}
function render(){const p=document.getElementById('player');if(!p||!ST.c)return;const ss=steps(ST.c),s=ss[ST.i];const title=ST.blind&&ST.i<11?'Blinded Rheumatology Case':ST.c.title;p.innerHTML=`<div class="rc7-hero"><span class="rc7-k">${esc(s.stage)}</span><h2>${esc(title)}</h2><p>${ST.blind&&ST.i<11?'Diagnosis hidden. Clinical information remains visible as the case unfolds.':'Progressive case-based learning.'}</p></div><div class="rc7-progress">${ss.map((_,i)=>`<span class="${i<ST.i?'done':i===ST.i?'now':''}"></span>`).join('')}</div><div class="rc7-card"><div class="rc7-info"><b>New information</b><br>${esc(s.reveal)}</div>${s.image?`<div class="rc7-image">${esc(s.image)}<br><small>Use an unannotated image first; teaching annotations can be shown after answering.</small></div>`:''}<div class="rc7-q">${esc(s.question)}</div><div>${s.opts.map((o,i)=>`<button class="rc7-opt" data-i="${i}">${esc(o)}</button>`).join('')}</div><div id="rc7fb"></div></div>`;p.querySelectorAll('.rc7-opt').forEach(b=>b.onclick=()=>answer(b,s))}
function answer(btn,s){if(document.querySelector('.rc7-next'))return;const chosen=s.opts[+btn.dataset.i],ok=chosen===s.correct;if(ok)ST.score++;ST.answers.push({q:s.question,chosen,correct:s.correct,ok});document.querySelectorAll('.rc7-opt').forEach(b=>{b.disabled=true;const txt=s.opts[+b.dataset.i];if(txt===s.correct)b.classList.add('good');else if(b===btn)b.classList.add('bad');else b.classList.add('dim')});const fb=document.getElementById('rc7fb');fb.innerHTML=`<div class="rc7-fb ${ok?'good':'try'}"><b>${ok?'✓ Good clinical reasoning.':'💡 Good attempt — review the discriminator.'}</b>${ok?'':`<br><b>Preferred answer:</b> ${esc(s.correct)}`}</div><button class="rc7-expbtn">💡 Explain why this answer is preferred <span style="float:right">⌄</span></button><div class="rc7-exp"><b>Why this answer fits</b><br>${esc(s.why)}${!ok?`<br><br><b>Why your answer is weaker</b><br>Your choice is less useful at this stage because it does not address the immediate clinical discriminator as directly as the preferred option.`:''}</div><button class="rc7-next">${ST.i===15?'Finish case':'Continue →'}</button>`;const eb=fb.querySelector('.rc7-expbtn'),ep=fb.querySelector('.rc7-exp');eb.onclick=()=>ep.classList.toggle('open');fb.querySelector('.rc7-next').onclick=()=>{if(ST.i===15)finish();else{ST.i++;render()}};setTimeout(()=>fb.scrollIntoView({behavior:'smooth',block:'nearest'}),60)}
function finish(){const sm=document.getElementById('summary');sm.innerHTML=`<div class="summaryHero"><div class="score">${ST.score}/16</div><b>${esc(ST.c.title)}</b><br><small>Case complete</small></div><div class="sectionTitle">Case synthesis</div><div class="rc7-card"><b>Presentation</b><br>${esc(ST.c.presentation)}<br><br><b>Examination</b><br>${esc(ST.c.exam)}<br><br><b>Investigations</b><br>${esc(ST.c.tests)}<br><br><b>Interpretation</b><br>${esc(ST.c.interpret)}<br><br><b>Management</b><br>${esc(ST.c.management)}</div><button class="rc7-next" id="rc7again">Try this case again</button><button class="secondary" id="rc7home">Back to cases</button>`;show('summary');sm.querySelector('#rc7again').onclick=()=>start(ST.c,ST.blind);sm.querySelector('#rc7home').onclick=()=>{show('home')}}
function mapCard(card){const t=(card.querySelector('b')?.textContent||card.textContent||'').trim();return CASES.find(c=>t.includes(c.title)||c.title.includes(t))||null}
document.addEventListener('click',e=>{const card=e.target.closest('.case,.rc5-case,.rc6-case');if(card&&!document.getElementById('home')?.classList.contains('hidden')){const c=mapCard(card);if(c){e.preventDefault();e.stopImmediatePropagation();start(c,false)}}},true);
window.startRandom=function(blind){const c=CASES[Math.floor(Math.random()*CASES.length)]||CASES[0];if(c)start(c,blind!==false)};
})();