(function(){
'use strict';
const css=document.createElement('style');css.textContent=`
.rca3-explainBtn{width:100%;border:1.5px solid var(--teal);background:#f7fbfb;color:var(--navy);border-radius:11px;padding:11px 12px;font-weight:850;text-align:left;margin:9px 0 4px}.rca3-explainBtn span{float:right;color:var(--teal)}.rca3-explain{display:none;border:1px solid var(--line);border-radius:12px;background:#fff;padding:12px 13px;margin:7px 0 10px;font-size:12.8px;line-height:1.5}.rca3-explain.open{display:block}.rca3-explain h4{margin:0 0 8px;color:var(--navy);font-size:14px}.rca3-good,.rca3-wrong,.rca3-principle{border-radius:9px;padding:9px 10px;margin:7px 0}.rca3-good{background:#edf8f2}.rca3-wrong{background:#fff3f2}.rca3-principle{background:#eef6f8}.rca3-good b{color:var(--green)}.rca3-wrong b{color:var(--red)}.rca3-principle b{color:var(--teal)}
`;document.head.appendChild(css);
function clean(s){return String(s||'').replace(/\s+/g,' ').trim()}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function rationale(q,correct,chosen,reveal){
 const t=(q+' '+correct+' '+reveal).toLowerCase();let why='This is the strongest answer because it directly addresses the clinical decision being asked and is most likely to change the differential or management.';let principle='Use each question to identify the single highest-yield discriminator before moving to broader testing or treatment.';
 if(/additional history|history would most improve/.test(t)){why='Before ordering tests, the history should first define the inflammatory pattern and look for disease-specific associated features. Chronology, symmetry, morning stiffness, psoriasis/nail disease, uveitis, IBD, preceding infection and family history can substantially re-rank the differential before any blood test is sent.';principle='In rheumatology, phenotype and associated-system history often have greater diagnostic value than a broad autoimmune panel. Testing should follow the clinical question, not create it.'}
 else if(/safety|red flag|urgent/.test(t)){why='This answer is best because time-critical mimics or organ-threatening disease must be addressed before routine diagnostic refinement. Missing infection, visual ischaemia, pulmonary–renal disease or severe neuromuscular involvement carries more immediate risk than delaying a non-urgent diagnosis.';principle='Safety outranks diagnostic elegance: identify emergencies first, then refine the rheumatological diagnosis.'}
 else if(/examination/.test(t)){why='The correct examination strategy tests the working phenotype while actively searching for clues to competing diagnoses. A narrow examination risks missing extra-articular features that may be more discriminating than the painful joint itself.';principle='Examination should confirm the syndrome and look for contradictory findings, not merely document tenderness.'}
 else if(/differential/.test(t)){why='The best answer keeps a short, clinically useful set of alternatives active and includes important mimics. This reduces premature closure while keeping the next investigation focused.';principle='A useful differential is not the longest list; it is the smallest list that explains the case and protects against dangerous alternatives.'}
 else if(/investigation|work.?up|test|order/.test(t)){why='This choice is preferred because it answers a specific diagnostic or safety question. Targeted tests provide more useful information than an indiscriminate panel and reduce incidental positives that can distract from the clinical phenotype.';principle='Before ordering a test, ask: what result am I expecting, and how would either result change what I do next?'}
 else if(/interpret/.test(t)){why='The result should be integrated with the history and examination rather than treated as a diagnosis in isolation. Serology, inflammatory markers and imaging modify probability; they do not replace clinical context.';principle='Interpret the pattern, not the isolated abnormality.'}
 else if(/most likely diagnosis|diagnosis/.test(t)){why='This diagnosis best integrates the chronology, examination and objective investigations available at this point, while leaving fewer important findings unexplained than the alternatives.';principle='Commit only after considering what evidence supports the diagnosis, what argues against it, and which dangerous mimic has been excluded.'}
 else if(/management|treat|therapy/.test(t)){why='The preferred option matches treatment intensity to disease severity, dominant clinical domain and safety considerations. It avoids treating the label alone without considering infection risk, organ involvement and contraindications.';principle='Treatment decisions should follow disease severity and organ threat, not just the diagnostic name.'}
 let wrong='';if(chosen&&clean(chosen)!==clean(correct)){wrong='Your selected option is understandable, but it is weaker because it either delays a higher-yield discriminator, narrows the assessment too early, or does not directly answer the clinical decision at this stage.';if(/defer associated-system questions/i.test(chosen))wrong='Deferring associated-system questions is weaker because features such as psoriasis, uveitis, IBD or a preceding GI/GU infection may be the key clues that separate the leading inflammatory arthritis diagnoses before imaging or serology.';if(/broad autoimmune panel/i.test(chosen))wrong='A broad autoimmune panel at this stage risks false-positive or incidental results and does not substitute for defining the clinical phenotype first.';}
 return{why,wrong,principle}
}
function enhance(){document.querySelectorAll('.rca2-feedback').forEach(fb=>{if(fb.dataset.rca3==='1')return;const card=fb.closest('.rca2-card')||fb.parentElement;const q=clean(card?.querySelector('.rca2-q')?.textContent);const reveal=clean(card?.querySelector('.rca2-reveal')?.textContent);const correct=clean(card?.querySelector('.rca2-opt.good')?.textContent);const chosen=clean(card?.querySelector('.rca2-opt.bad')?.textContent)||clean(card?.querySelector('.rca2-opt.good')?.textContent);if(!q||!correct)return;fb.dataset.rca3='1';const r=rationale(q,correct,chosen,reveal);const b=document.createElement('button');b.type='button';b.className='rca3-explainBtn';b.innerHTML='💡 Why is this the best answer?<span>⌄</span>';const p=document.createElement('div');p.className='rca3-explain';p.innerHTML='<h4>Answer explanation</h4><div class="rca3-good"><b>Why this answer is stronger</b><br>'+esc(r.why)+'</div>'+(r.wrong?'<div class="rca3-wrong"><b>Why the selected alternative is weaker</b><br>'+esc(r.wrong)+'</div>':'')+'<div class="rca3-principle"><b>Clinical reasoning principle</b><br>'+esc(r.principle)+'</div>';b.onclick=()=>{const open=p.classList.toggle('open');b.querySelector('span').textContent=open?'⌃':'⌄';if(open)setTimeout(()=>p.scrollIntoView({behavior:'smooth',block:'nearest'}),60)};fb.insertAdjacentElement('afterend',b);b.insertAdjacentElement('afterend',p)})}
let tm;new MutationObserver(()=>{clearTimeout(tm);tm=setTimeout(enhance,80)}).observe(document.body,{subtree:true,childList:true,classList:true});setTimeout(enhance,300);
})();