(function(){
'use strict';

const css=document.createElement('style');
css.textContent=`
.rca2-banner{background:linear-gradient(135deg,var(--navy),#174a68);color:#fff;border-radius:15px;padding:16px;margin-bottom:12px}.rca2-banner h2{margin:5px 0 7px;font-size:20px}.rca2-banner p{margin:0;color:#d8e8e8;line-height:1.5;font-size:13px}.rca2-kicker{display:inline-block;background:#edf7f6;color:var(--teal);border-radius:999px;padding:5px 9px;font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.5px}.rca2-reveal{background:#eef7f6;border-left:5px solid var(--teal);border-radius:11px;padding:11px 12px;margin:10px 0;color:var(--ink);font-size:13px;line-height:1.5}.rca2-reveal b{color:var(--navy)}.rca2-card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:14px;margin-bottom:12px}.rca2-q{font-size:17px;font-weight:900;color:var(--navy);line-height:1.35;margin:8px 0 12px}.rca2-opt{display:block;width:100%;text-align:left;border:1.5px solid var(--line);border-radius:11px;padding:12px;margin:8px 0;background:#fff;color:var(--ink);font-size:13.2px;font-weight:650}.rca2-opt.good{background:var(--greenbg);border-color:var(--green);color:var(--green)}.rca2-opt.bad{background:var(--redbg);border-color:var(--red);color:var(--red)}.rca2-opt.dim{opacity:.65}.rca2-feedback{border-radius:11px;padding:12px;margin:10px 0;font-size:13px;line-height:1.5}.rca2-feedback.good{background:var(--greenbg);color:var(--green)}.rca2-feedback.try{background:var(--amberbg);color:var(--amber)}.rca2-next{width:100%;border:0;border-radius:11px;background:var(--navy);color:#fff;padding:13px;font-weight:900;margin-top:8px}.rca2-progress{display:flex;gap:4px;margin:10px 0 12px}.rca2-progress span{height:7px;flex:1;border-radius:5px;background:#dde8e8}.rca2-progress .done{background:var(--teal)}.rca2-progress .now{background:var(--navy)}.rca2-section{font-size:10.5px;letter-spacing:.65px;text-transform:uppercase;color:var(--teal);font-weight:900;margin-bottom:5px}.rca2-image{border:2px dashed #9eb8b7;border-radius:12px;background:#fbfdfd;color:#587176;padding:15px;margin:10px 0;text-align:center;font-size:12px;line-height:1.45}.rca2-summaryItem{border:1px solid var(--line);border-radius:11px;padding:11px 12px;margin:8px 0;background:#fff}.rca2-summaryItem.ok{border-left:5px solid var(--green)}.rca2-summaryItem.no{border-left:5px solid var(--red)}.rca2-summaryItem .st{font-weight:900;margin-bottom:5px}.rca2-summaryItem.ok .st{color:var(--green)}.rca2-summaryItem.no .st{color:var(--red)}.rca2-actions{display:flex;gap:8px;flex-wrap:wrap}.rca2-actions button{flex:1 1 160px}.rca2-note{font-size:11.5px;color:var(--muted);line-height:1.45}.rca2-hidden{display:none!important}@media(max-width:620px){.rca2-banner{padding:14px}.rca2-q{font-size:16px}.rca2-opt{font-size:12.8px;padding:11px}.rca2-actions{display:block}.rca2-actions button{width:100%;margin-top:7px}}
`;
document.head.appendChild(css);

function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function parseCases(){try{return raw.trim().split(/\n+/).map(line=>{const p=line.split('|');return{id:+p[0],title:p[1],cat:p[2],level:p[3],presentation:p[4],exam:p[5],tests:p[6],image:p[7],diff:p[8],interpret:p[9],management:p[10],monitor:p[11],module:p[12]}}).filter(x=>x.id&&x.title)}catch(e){return[]}}
const RCASE=parseCases();
let S={c:null,blind:false,step:0,answers:[],score:0};
const STAGES=['History','History','Safety','Examination','Differential','Work-up','Investigations','Work-up','Imaging / pathology','Interpretation','Diagnosis','Diagnostic framework','Management','Treatment safety','Organ / comorbidity screening','Monitoring','Escalation','Consolidation'];

function categoryHistory(c){
 const m={ia:'Clarify inflammatory chronology, symmetry, morning stiffness, psoriasis/nail disease, uveitis, IBD, infection triggers and family history.',crystal:'Clarify speed of onset, previous attacks, fever, skin breach/prosthesis, CKD/diuretics, alcohol/diet and infection risks.',ctd:'Ask about photosensitivity, Raynaud phenomenon, oral ulcers, sicca, serositis, thrombosis/pregnancy history, renal and neurologic symptoms.',vasc:'Ask systematically about visual/cranial symptoms, ENT disease, pulmonary symptoms, haematuria, neuropathy, skin lesions and constitutional symptoms.',myo:'Distinguish true weakness from pain/fatigue; ask about dysphagia, dyspnoea, rash, Raynaud, drugs and malignancy clues.',pain:'Clarify activity relationship, duration of stiffness, sleep, fatigue, functional pattern, focal neurological symptoms and inflammatory red flags.',systemic:'Clarify chronology, constitutional features, organ involvement, infection exposure, malignancy clues and medication history.'};return m[c.cat]||m.systemic
}
function categoryExam(c){
 const m={ia:'Perform a full joint count plus skin, scalp, nails, entheses, dactylitis, spine/SI and extra-articular examination.',crystal:'Examine the involved joint for effusion/warmth and look for tophi, infection source, other involved joints and systemic sepsis features.',ctd:'Examine skin, mucosa, hands/nails, glands, joints, cardiopulmonary system, neurology and signs of renal/vascular involvement.',vasc:'Examine pulses/BP symmetry, temporal arteries where relevant, skin, ENT, chest, renal status, peripheral nerves and eyes.',myo:'Document objective proximal/distal power, neck flexion, swallowing/respiratory status, rash, joints and lung findings.',pain:'Localise pain anatomically, assess range of motion, focal tenderness, neurological signs, objective synovitis and widespread tenderness.',systemic:'Use a complete general and system examination targeted to the organs suggested by the history.'};return m[c.cat]||m.systemic
}
function initialTests(c){
 const m={ia:'FBC, renal/liver profile, ESR/CRP and targeted RF/ACPA where relevant; then imaging/aspiration driven by the phenotype.',crystal:'If a hot swollen joint is accessible, aspirate for cell count, crystals, Gram stain and culture; add renal profile, inflammatory markers and serum urate in context.',ctd:'FBC, renal/liver profile, urinalysis/protein quantification, ESR/CRP and phenotype-directed ANA/ENA/dsDNA/complement or APS testing.',vasc:'FBC, renal/liver profile, ESR/CRP, urinalysis/protein, chest assessment and mechanism-directed ANCA/cryoglobulin/complement testing; biopsy/imaging if indicated.',myo:'CK/aldolase, AST/ALT/LDH, inflammatory markers, myositis antibodies where appropriate, urinalysis and targeted pulmonary/cardiac assessment.',pain:'Use focused testing only where red flags or inflammatory features justify it; avoid broad autoimmune panels for a mechanical/nociplastic phenotype.',systemic:'Order a focused baseline panel and then tests that discriminate the leading diagnoses rather than a shotgun screen.'};return m[c.cat]||m.systemic
}
function urgent(c){const t=c.title.toLowerCase();if(/septic/.test(t))return'Hot swollen joint with fever/rigors: urgent aspiration, cultures and sepsis management take priority.';if(/giant cell|gca/.test(t))return'Visual symptoms or jaw claudication make this time-critical: protect vision and arrange urgent specialist assessment.';if(/gpa|mpa|polyangiitis|vascul/.test(t)&&/renal|pulmonary|gpa|mpa/.test((c.presentation+' '+c.tests).toLowerCase()))return'Potential organ-threatening vasculitis requires urgent renal/pulmonary assessment and senior specialist involvement.';if(/myositis|antisynthetase|dermatomy/.test(t))return'Dysphagia, respiratory weakness, myocarditis or rapidly progressive ILD would make this urgent.';return'No immediate emergency is established yet, but actively check for infection, organ-threatening inflammation and neurological/vascular compromise.'}
function organScreen(c){return c.monitor||'Screen relevant organ involvement and treatment risks before finalising therapy.'}
function escalation(c){const t=c.title.toLowerCase();if(/gout|cppd|septic/.test(t))return'Escalate if sepsis features, persistent fever, bacteraemia risk or failure to improve raise concern for infection.';if(/vascul|gca|polyangiitis|takayasu/.test(t))return'Escalate urgently for visual loss, pulmonary haemorrhage, rapidly worsening renal function, digital/limb ischaemia or major neurological involvement.';if(/myositis|antisynthetase|dermatomy/.test(t))return'Escalate for dysphagia, respiratory compromise, myocarditis, rapidly progressive ILD or severe weakness.';if(/lupus|sclerosis|sjog|mctd|ctd/.test(t))return'Escalate for major renal, neurological, cardiopulmonary or vascular organ involvement.';return'Escalate if new red flags, rapid deterioration, treatment toxicity or major organ involvement develops.'}
function diagnosticOptions(c){const d=(c.diff||'').split(';').map(x=>x.trim()).filter(Boolean);return shuffle([c.title,...d,'Medication-related / infectious mimic','Mechanical or nociplastic pain syndrome'].filter((x,i,a)=>x&&a.indexOf(x)===i)).slice(0,5)}
function distract(correct,type){
 const banks={history:['Order a broad autoimmune panel immediately before clarifying the history','Focus only on pain severity and analgesia use','Defer associated-system questions until after imaging'],exam:['Limit examination to the single most painful joint','Perform no examination if inflammatory markers are raised','Examine only for tender points'],tests:['Order ANA, ANCA, RF, ACPA, HLA-B27 and myositis antibodies in every case','Repeat all blood tests before obtaining any focused sample or imaging','Request whole-body CT as the first investigation'],interpret:['Treat any positive autoantibody as diagnostic regardless of phenotype','Assume normal inflammatory markers exclude inflammatory rheumatic disease','Choose the diagnosis solely from age and sex'],management:['Start long-term immunosuppression before resolving major infection risk','Use treatment response alone as the diagnostic test','Delay all management until every possible investigation is complete'],monitor:['Monitor symptoms only; objective disease activity and toxicity checks are unnecessary','Stop follow-up once symptoms improve','Repeat broad autoantibody panels routinely to measure treatment response']};return shuffle([correct,...(banks[type]||banks.interpret)]).slice(0,4)}

function steps(c){return [
 {stage:'History',reveal:'Initial presentation: '+c.presentation,q:'Before ordering tests, which additional history would most improve diagnostic discrimination?',opts:distract(categoryHistory(c),'history'),a:0,ex:'A high-yield rheumatology history should define chronology, inflammatory behaviour and associated organ/extra-articular features before testing.'},
 {stage:'History',reveal:'You clarify the chronology and associated features.',q:'Which approach best frames the problem at this stage?',opts:distract('Build a syndrome/phenotype first, keep several plausible diagnoses active, and identify the next discriminator.','interpret'),a:0,ex:'This avoids premature closure and makes subsequent investigations purposeful.'},
 {stage:'Safety',reveal:'The case is still evolving. No diagnosis has been disclosed.',q:'What safety question should be addressed before routine work-up continues?',opts:distract(urgent(c),'interpret'),a:0,ex:'Rheumatology presentations can hide infection, vascular ischaemia or organ-threatening inflammatory disease.'},
 {stage:'Examination',reveal:'Focused examination findings are now available: '+c.exam,q:'Which examination strategy best complements these findings?',opts:distract(categoryExam(c),'exam'),a:0,ex:'Examination should test the working phenotype and actively look for clues that favour competing diagnoses.'},
 {stage:'Differential',reveal:'History and examination are now combined. Diagnosis remains hidden.',q:'Which differential set best fits the information available so far?',opts:distract(c.diff||'Inflammatory, infectious, crystal and mechanical mimics should remain active.','interpret'),a:0,ex:'A good differential is short enough to be useful but broad enough to protect against important mimics.'},
 {stage:'Work-up',reveal:'You now need to choose an initial investigation strategy.',q:'Which investigation plan is most appropriate next?',opts:distract(initialTests(c),'tests'),a:0,ex:'Targeted investigations should answer a specific diagnostic or safety question; broad untargeted panels create noise.'},
 {stage:'Investigations',reveal:'Results return: '+c.tests,q:'How should these results be interpreted?',opts:distract('Integrate the results with the clinical phenotype; use them to re-rank the differential rather than treating any single result as diagnostic.','interpret'),a:0,ex:'Serology, inflammatory markers and imaging are probability modifiers, not substitutes for clinical reasoning.'},
 {stage:'Work-up',reveal:'The first-line results narrow the field but do not end the case.',q:'What is the best next diagnostic move?',opts:distract('Choose the single test, sample or imaging study that best separates the two leading diagnoses and would change management.','tests'),a:0,ex:'This is the key NephSim-style step: decide what information you need next, rather than simply reading a prebuilt panel.'},
 {stage:'Imaging / pathology',reveal:'Additional diagnostic material becomes available.',image:c.image,q:'Before seeing an annotation, what should you do with this image/pathology result?',opts:distract('Describe the objective pattern first, then decide whether it supports inflammation, degeneration, crystal disease, infection, vascular injury or another process.','interpret'),a:0,ex:'Description before diagnosis reduces pattern-recognition bias.'},
 {stage:'Interpretation',reveal:'You now have history, examination, laboratory data and imaging/pathology information.',q:'Which interpretation best synthesises the case so far?',opts:distract(c.interpret,'interpret'),a:0,ex:'The strongest interpretation explains the greatest number of findings while leaving the fewest important contradictions.'},
 {stage:'Diagnosis',reveal:'Commit point: the diagnosis is still hidden until you answer.',q:'What is the most likely diagnosis?',opts:diagnosticOptions(c),correctText:c.title,ex:'This is the point to commit after progressively reviewing the evidence rather than being told the answer at the start.'},
 {stage:'Diagnostic framework',reveal:'Diagnosis revealed: '+c.title,q:'What is the best way to use formal criteria now?',opts:distract('Use criteria to standardise/classify where applicable, but keep diagnosis grounded in the complete clinical picture and exclusion of important mimics.','interpret'),a:0,ex:'Classification criteria and clinical diagnosis are related but not interchangeable.'},
 {stage:'Management',reveal:'You now need to move from diagnosis to management.',q:'Which management direction best fits this case?',opts:distract(c.management,'management'),a:0,ex:'Management should reflect disease severity, dominant domain, comorbidity and urgency rather than diagnosis alone.'},
 {stage:'Treatment safety',reveal:'Before treatment is finalised, safety screening is required.',q:'Which principle is most appropriate?',opts:distract('Check infection risk, relevant baseline laboratory/organ status, vaccination needs, pregnancy potential where relevant, drug interactions and treatment-specific contraindications.','management'),a:0,ex:'The safest treatment choice depends on the patient context as well as the disease label.'},
 {stage:'Organ / comorbidity screening',reveal:'The diagnosis may have extra-articular or systemic implications.',q:'What should be actively screened or documented?',opts:distract(organScreen(c),'monitor'),a:0,ex:'A rheumatology diagnosis is often incomplete until relevant organ involvement and comorbidity have been assessed.'},
 {stage:'Monitoring',reveal:'Treatment has been initiated and follow-up is planned.',q:'Which monitoring strategy is most appropriate?',opts:distract(c.monitor,'monitor'),a:0,ex:'Follow-up should measure both effectiveness and harm with objective disease activity where possible.'},
 {stage:'Escalation',reveal:'The patient is being followed longitudinally.',q:'Which development should trigger urgent reassessment or escalation?',opts:distract(escalation(c),'interpret'),a:0,ex:'Knowing when a seemingly routine rheumatology case becomes urgent is a core part of safe practice.'},
 {stage:'Consolidation',reveal:'You have worked from presentation through diagnosis and management.',q:'Which summary best describes the reasoning process used in this case?',opts:distract('Phenotype first → targeted examination → purposeful investigations → interpretation in context → diagnostic commitment → severity-directed treatment and monitoring.','interpret'),a:0,ex:'That sequence is the intended educational model for Rheum Case Assist.'}
 ]}
function correctIndex(step){if(step.correctText)return step.opts.findIndex(x=>x===step.correctText);return 0}
function showOnly(id){['home','player','summary','about'].forEach(x=>document.getElementById(x)?.classList.toggle('hidden',x!==id));window.scrollTo(0,0)}
function start(c,blind){S={c,blind:!!blind,step:0,answers:[],score:0};showOnly('player');renderStep()}
function renderStep(){const p=document.getElementById('player');if(!p||!S.c)return;const ss=steps(S.c),st=ss[S.step];const title=S.blind&&S.step<11?'Blinded Rheumatology Case':S.c.title;const prog=ss.map((_,i)=>`<span class="${i<S.step?'done':i===S.step?'now':''}"></span>`).join('');p.innerHTML=`<div class="rca2-banner"><span class="rca2-kicker">${esc(st.stage)}</span><h2>${esc(title)}</h2><p>${S.blind&&S.step<11?'Diagnosis hidden — the clinical vignette and new information remain visible as the case unfolds.':'Progressive rheumatology case learning.'}</p></div><div class="rca2-progress">${prog}</div><div class="rca2-card"><div class="rca2-section">Step ${S.step+1} of ${ss.length}</div><div class="rca2-reveal"><b>New information</b><br>${esc(st.reveal)}</div>${st.image?`<div class="rca2-image">${esc(st.image)}<br><small>Image remains unannotated during the question; annotations/teaching labels can be revealed after commitment.</small></div>`:''}<div class="rca2-q">${esc(st.q)}</div><div id="rca2Opts">${shuffle(st.opts.map((x,i)=>({x,orig:i}))).map(o=>`<button class="rca2-opt" data-orig="${o.orig}">${esc(o.x)}</button>`).join('')}</div><div id="rca2Fb"></div></div>`;p.querySelectorAll('.rca2-opt').forEach(b=>b.onclick=()=>answer(b,st))}
function answer(btn,st){if(document.querySelector('.rca2-next'))return;const correct=correctIndex(st);const chosen=+btn.dataset.orig;const ok=chosen===correct;if(ok)S.score++;S.answers.push({step:S.step,q:st.q,chosen:st.opts[chosen],correct:st.opts[correct],ok,ex:st.ex});document.querySelectorAll('.rca2-opt').forEach(b=>{b.disabled=true;const i=+b.dataset.orig;if(i===correct)b.classList.add('good');else if(b===btn)b.classList.add('bad');else b.classList.add('dim')});const fb=document.getElementById('rca2Fb');fb.innerHTML=`<div class="rca2-feedback ${ok?'good':'try'}"><b>${ok?'✓ Good clinical reasoning.':'💡 Good attempt — reconsider this discriminator.'}</b><br>${esc(st.ex)}${ok?'':`<br><br><b>Stronger choice:</b> ${esc(st.opts[correct])}`}</div><button class="rca2-next">${S.step===17?'Finish case':'Continue →'}</button>`;fb.querySelector('.rca2-next').onclick=()=>{if(S.step>=17)finish();else{S.step++;renderStep()}};setTimeout(()=>fb.scrollIntoView({behavior:'smooth',block:'nearest'}),80)}
function finish(){const sm=document.getElementById('summary');const rows=S.answers.map((a,i)=>`<div class="rca2-summaryItem ${a.ok?'ok':'no'}"><div class="st">${a.ok?'✅ Correct':'❌ 💡 Review'} — Step ${i+1}</div><b>${esc(a.q)}</b><br><span class="rca2-note">Your answer: ${esc(a.chosen)}${a.ok?'':`<br>Stronger answer: ${esc(a.correct)}`}<br>${esc(a.ex)}</span></div>`).join('');sm.innerHTML=`<div class="summaryHero"><div class="score">${S.score}/18</div><b>${esc(S.c.title)}</b><br><span class="rca2-note" style="color:#d8e8e8">Progressive case complete</span></div><div class="sectionTitle">Case synthesis</div><div class="rca2-card"><b>Presentation</b><br>${esc(S.c.presentation)}<br><br><b>Examination</b><br>${esc(S.c.exam)}<br><br><b>Investigations</b><br>${esc(S.c.tests)}<br><br><b>Interpretation</b><br>${esc(S.c.interpret)}<br><br><b>Management</b><br>${esc(S.c.management)}</div><div class="sectionTitle">Step-by-step review</div>${rows}<div class="rca2-actions"><button class="primary" id="rca2Retry">Try this case again</button><button class="secondary" id="rca2Blind">Another blinded case</button><button class="secondary" id="rca2Home">Back to cases</button></div>`;showOnly('summary');sm.querySelector('#rca2Retry').onclick=()=>start(S.c,S.blind);sm.querySelector('#rca2Blind').onclick=()=>window.startRandom(true);sm.querySelector('#rca2Home').onclick=()=>{if(typeof window.goHome==='function')window.goHome();else showOnly('home')}}

window.startRandom=function(blind){let pool=RCASE;try{const lev=document.querySelector('#home select');if(lev&&/easy|intermediate|advanced/i.test(lev.value)&&!/any|all/i.test(lev.value))pool=pool.filter(c=>c.level.toLowerCase()===lev.value.toLowerCase())}catch(e){}const c=pool[Math.floor(Math.random()*pool.length)]||RCASE[0];start(c,blind!==false)};

document.addEventListener('click',function(e){const card=e.target.closest('.case');if(!card||document.getElementById('home')?.classList.contains('hidden'))return;const tx=(card.querySelector('b')?.textContent||card.textContent||'').trim();const c=RCASE.find(x=>tx.includes(x.title)||x.title.includes(tx));if(!c)return;e.preventDefault();e.stopImmediatePropagation();start(c,false)},true);

const note=document.createElement('div');note.className='rca2-note';note.id='rca2EducationalNote';note.textContent='Case engine v2: the vignette remains visible in blinded mode. Information is revealed progressively through history, examination, targeted work-up, investigation interpretation, imaging/pathology, diagnosis, treatment and monitoring.';
function addNote(){const h=document.getElementById('home');if(h&&!document.getElementById('rca2EducationalNote'))h.prepend(note)}
let tm;new MutationObserver(()=>{clearTimeout(tm);tm=setTimeout(addNote,100)}).observe(document.body,{subtree:true,childList:true});setTimeout(addNote,300);
})();