(function(){
const style=document.createElement('style');style.textContent=`
.dx-rank{display:flex;align-items:flex-start;gap:12px}.dx-rank-num{min-width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:var(--teal);color:#fff;font-weight:800;font-size:18px}.dx-rank-main{flex:1;min-width:0}.dx-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.dx-actions .btn{width:auto;padding:9px 13px;font-size:13px}.test-link{appearance:none;border:1px solid var(--line);background:#fff;border-radius:9px;padding:8px 10px;text-align:left;cursor:pointer;color:var(--navy);font:inherit;width:100%;margin:4px 0}.test-link:hover{border-color:var(--teal);background:#f3fbfb}.test-link b{color:var(--teal)}.module-focus{outline:3px solid rgba(14,124,123,.25);scroll-margin-top:90px}.evidence-modal{position:fixed;inset:0;background:rgba(11,46,79,.45);z-index:9999;display:none;align-items:center;justify-content:center;padding:18px}.evidence-modal.open{display:flex}.evidence-dialog{max-width:700px;width:100%;max-height:82vh;overflow:auto;background:#fff;border-radius:16px;padding:20px;box-shadow:0 20px 60px rgba(0,0,0,.25)}.evidence-dialog h3{margin-top:0}.evidence-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.evidence-stat{padding:10px;border:1px solid var(--line);border-radius:10px;background:#f8fbfb}.evidence-stat strong{display:block;font-size:20px;color:var(--teal)}@media(max-width:620px){.evidence-grid{grid-template-columns:1fr}.dx-rank{gap:9px}.dx-rank-num{min-width:36px;height:36px;font-size:16px}}
`;document.head.appendChild(style);

const testEvidence=[
 {re:/anti[- ]?ccp|acpa/i,name:'Anti-CCP / ACPA',sens:'~67–72%',spec:'~95–96%',context:'Meta-analyses show moderate sensitivity and high specificity for rheumatoid arthritis; estimates vary by assay, disease duration and study design. A negative result does not exclude RA.',source:'Nishimura et al., Ann Intern Med 2007; Whiting et al., Clin Chem 2018.'},
 {re:/\brf\b|rheumatoid factor/i,name:'Rheumatoid factor',sens:'~69%',spec:'~85%',context:'Pooled estimates are less specific than anti-CCP. RF may be positive in other autoimmune disease, chronic infection and with increasing age; interpret titre and phenotype together.',source:'Nishimura et al., Ann Intern Med 2007.'},
 {re:/hla[- ]?b27/i,name:'HLA-B27',sens:'~68%*',spec:'~88%*',context:'*Recent systematic-review estimates in suspected axial spondyloarthritis; certainty was rated very low and performance varies substantially by ancestry, prevalence and referral population. It is a susceptibility marker, not a stand-alone diagnostic test.',source:'2026 systematic review, PubMed PMID 42454151.'},
 {re:/2010.*acr.*eular|acr.*eular.*ra|ra classification/i,name:'2010 ACR/EULAR RA classification framework',sens:'~80–82%',spec:'~61%',context:'These are classification-performance estimates, not the sensitivity/specificity of a diagnostic test. The framework is intended for patients with clinical synovitis not better explained by another diagnosis.',source:'Sakellariou et al., PLoS One 2013; Radner et al., Ann Rheum Dis 2014.'},
 {re:/2015.*gout|gout classification/i,name:'2015 ACR/EULAR gout classification criteria',sens:'92%',spec:'89%',context:'Validation performance of the full classification criteria. MSU crystals in a symptomatic joint/bursa or tophus are a sufficient classification criterion. This performance should not be transferred to a single imaging or laboratory test.',source:'Neogi et al., Arthritis Rheumatol / Ann Rheum Dis 2015.'},
 {re:/2023.*cppd|cppd.*classification/i,name:'2023 ACR/EULAR CPPD classification criteria',sens:'99.2%',spec:'92.5%',context:'Validation-cohort performance of the complete CPPD classification framework. Derivation performance was 92.2% sensitivity and 87.9% specificity. These are classification, not stand-alone diagnostic-test, characteristics.',source:'Abhishek et al., Arthritis Rheumatol 2023.'},
 {re:/synovial.*crystal|crystal.*synovial|msu crystal|calcium pyrophosphate crystals/i,name:'Synovial-fluid crystal analysis',sens:'Variable',spec:'High when crystals are correctly identified',context:'Performance depends on timing, sample handling, crystal burden and examiner expertise. A false-negative aspirate can occur. When infection is possible, crystals do not remove the need for Gram stain/culture.',source:'Disease-specific guideline/criteria context; no single universal sensitivity/specificity value is valid.'},
 {re:/gram stain|culture|blood culture/i,name:'Microbiological testing for septic arthritis',sens:'Variable',spec:'Usually high for a true positive culture',context:'Sensitivity depends on prior antibiotics, organism, specimen quality and culture methods. A negative Gram stain or culture does not by itself exclude septic arthritis when clinical suspicion remains high.',source:'Performance is context-dependent; use local microbiology standards and septic-arthritis guidance.'},
 {re:/mri.*si|si[- ]joint imaging|sacroili/i,name:'SI-joint MRI / imaging for axial SpA',sens:'Context-dependent',spec:'Context-dependent',context:'There is no single valid sensitivity/specificity to apply across readers, sequences and patient populations. MRI bone-marrow oedema is not disease-specific and must be interpreted with the clinical phenotype and structural lesions.',source:'Use current ASAS/EULAR imaging guidance and local radiology expertise.'},
 {re:/ultrasound|dect|dual-energy ct/i,name:'Musculoskeletal imaging test',sens:'Context-dependent',spec:'Context-dependent',context:'Diagnostic accuracy depends on the target lesion, machine, operator, disease stage and reference standard. The app should show disease- and modality-specific evidence rather than a universal number.',source:'Use disease-specific EULAR/ACR imaging evidence.'}
];
function evidenceForTest(label){return testEvidence.find(x=>x.re.test(label))||{name:label,sens:'Not established as one universal value',spec:'Not established as one universal value',context:'Sensitivity and specificity depend on the exact indication, threshold, disease stage, comparator population and reference standard. A single number would be misleading. Use the test to answer a defined clinical question.',source:'No single validated universal estimate stored in this build.'}}
function ensureModal(){if(document.getElementById('testEvidenceModal'))return;const m=document.createElement('div');m.id='testEvidenceModal';m.className='evidence-modal';m.innerHTML='<div class="evidence-dialog" role="dialog" aria-modal="true" aria-labelledby="testEvidenceTitle"><button class="btn secondary" style="float:right;width:auto" onclick="closeTestEvidence()">Close</button><h3 id="testEvidenceTitle">Test evidence</h3><div id="testEvidenceBody"></div></div>';m.addEventListener('click',e=>{if(e.target===m)closeTestEvidence()});document.body.appendChild(m)}
window.closeTestEvidence=function(){document.getElementById('testEvidenceModal')?.classList.remove('open')};
window.showTestEvidence=function(label){ensureModal();const d=evidenceForTest(label);document.getElementById('testEvidenceTitle').textContent=d.name;document.getElementById('testEvidenceBody').innerHTML=`<div class="evidence-grid"><div class="evidence-stat"><span>Sensitivity</span><strong>${escapeHtml(d.sens)}</strong></div><div class="evidence-stat"><span>Specificity</span><strong>${escapeHtml(d.spec)}</strong></div></div><p class="small">${escapeHtml(d.context)}</p><div class="minihead">Evidence source / caveat</div><div class="small">${escapeHtml(d.source)}</div><div class="card warning" style="margin:12px 0 0"><span class="small"><b>Clinical-use caution:</b> predictive value changes with pre-test probability. Classification-criteria performance is not interchangeable with diagnostic-test performance.</span></div>`;document.getElementById('testEvidenceModal').classList.add('open')};
function testButton(t){return `<button type="button" class="test-link" onclick='showTestEvidence(${JSON.stringify(t)})'><b>Test / investigation:</b> ${escapeHtml(t)}<br><span class="tiny">Click for sensitivity, specificity and interpretation caveats</span></button>`}

window.openModule=function(key){showScreen('criteria',document.querySelectorAll('.tab')[2]);setTimeout(()=>{document.querySelectorAll('.module-focus').forEach(x=>x.classList.remove('module-focus'));const el=document.getElementById('module-'+key);if(el){el.classList.add('module-focus');el.scrollIntoView({behavior:'smooth',block:'start'})}},30)};

renderDifferentials=function(scored,text,age){
 let ranked=scored.filter(m=>m.score>=10).slice(0,4);const peripheral=/(?:knee|ankle|wrist|elbow|mcp|pip).{0,15}(?:swelling|synovitis)|(?:swelling|synovitis).{0,15}(?:knee|ankle|wrist|elbow|mcp|pip)|swollen joint|joint swelling/i.test(text);
 if(peripheral){['earlyarthritis','seronegativeia'].forEach(k=>{const c=scored.find(m=>m.key===k);if(c&&!ranked.some(x=>x.key===k)){if(ranked.length>=4)ranked.pop();ranked.push(c)}});ranked.sort((a,b)=>b.score-a.score)}
 if(ranked.length<3){for(const c of scored){if(!ranked.some(x=>x.key===c.key))ranked.push(c);if(ranked.length>=3)break}}
 ranked=ranked.slice(0,4);
 let html='<div class="card small"><b>How to use this list:</b> these are the 3–4 leading diagnostic candidates generated from the supplied phenotype. Rank reflects the current heuristic signal, not a diagnosis or probability. Review the points for and against each candidate and decide which best fits the patient.</div>';
 ranked.forEach((m,i)=>{const supp=uniq([...(m.hits||[]).map(h=>'Case feature detected: '+h),...(m.support||[])]).slice(0,5);const ag=uniq([...caseSpecificAgainst(m,text,age),...(m.against||[])]).slice(0,5);const dis=(m.missing||[]).slice(0,4);html+=`<div class="card dx"><div class="dx-rank"><div class="dx-rank-num">${i+1}</div><div class="dx-rank-main"><h3 style="margin-top:0">${escapeHtml(m.label)}</h3><div class="like ${cls(m.score)}">${likelihood(m.score)} · ${m.score}/100 heuristic signal</div><div class="minihead">Why this diagnosis is possible — FOR</div><ul>${supp.map(x=>`<li>${escapeHtml(x)}</li>`).join('')||'<li>No strong disease-specific positive feature has yet been supplied.</li>'}</ul><div class="minihead">Why it may be less likely — AGAINST / ATYPICAL</div><ul>${ag.map(x=>`<li>${escapeHtml(x)}</li>`).join('')||'<li>No major contradictory feature has been identified from the supplied information; this does not mean none is present.</li>'}</ul><div class="minihead">What would help discriminate it</div><ul>${dis.map(x=>`<li>${escapeHtml(x)}</li>`).join('')||'<li>Clarify chronology, objective examination and disease-specific investigations.</li>'}</ul><div class="dx-actions"><button class="btn secondary" type="button" onclick="openModule('${m.key}')">Open ${escapeHtml(m.label)} module & tests</button></div></div></div></div>`});document.getElementById('differentials').innerHTML=html
};

renderTests=function(scored,text){let top=scored.filter(m=>m.score>=10).slice(0,4);if(top.length<3)top=scored.slice(0,3);let ts=[];top.forEach(m=>(m.tests||[]).slice(0,3).forEach(x=>ts.push(x)));if(scored.some(m=>vasculitisModuleKeys.has(m.key)&&m.score>=18)){ts.unshift('Suspected vasculitis: define vessel size and organ extent first; obtain FBC, ESR/CRP, renal/liver profile and urinalysis with microscopy/protein, then choose mechanism-specific tests rather than a shotgun panel.')}ts=uniq(ts).slice(0,14);document.getElementById('tests').innerHTML=ts.length?ts.map(t=>`<li style="list-style:none;margin-left:-18px">${testButton(t)}</li>`).join(''):'<li>Start with history and examination to define inflammatory versus mechanical pattern before ordering broad panels.</li>'};

renderCriteria=function(){let html='';modules.filter(m=>m.key!=='urgent').forEach(m=>{html+=`<div class="card" id="module-${m.key}"><span class="chip">${escapeHtml(m.group)}</span><b>${escapeHtml(m.label)}</b><div class="small" style="margin-top:8px">${(m.support||[]).map(escapeHtml).join(' · ')}</div><div class="minihead">Classification / diagnostic framework</div><div class="small">${escapeHtml(m.criteria||'No module-specific criteria summary available.')}</div><div class="minihead">Core work-up prompts</div><ul>${(m.missing||[]).slice(0,6).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul><div class="minihead">Additional diagnostic tests / investigations</div><div>${(m.tests||[]).map(testButton).join('')||'<div class="small">No module-specific tests stored yet.</div>'}</div></div>`});document.getElementById('criteriaCards').innerHTML=html};

try{sourceDecks.push(['Ranked differential & test evidence v14','Outputs 3–4 prioritised differential candidates with explicit FOR / AGAINST points, direct module links, and clickable investigation cards. Sensitivity/specificity values are shown only where a defensible evidence estimate is stored; otherwise the app explicitly states that performance is context-dependent.']);renderCriteria();renderSources()}catch(e){console.warn(e)}
})();