(function(){
const style=document.createElement('style');style.textContent=`
.analysis-state-ready{background:#d99a16!important;border-color:#c78a0d!important;color:#fff!important;transition:background .2s ease,border-color .2s ease,transform .12s ease}.analysis-state-done{background:#23834f!important;border-color:#1d7144!important;color:#fff!important}.analysis-state-done:after{content:'  ✓';font-weight:900}.analysis-next-hint{margin:8px 2px 0;font-size:13px;line-height:1.35;color:#5c6d76}.analysis-next-hint.done{color:#1d7144;font-weight:700}.analysis-state-ready:active,.analysis-state-done:active{transform:scale(.99)}
`;document.head.appendChild(style);

function findAnalyseButton(){return [...document.querySelectorAll('button')].find(b=>/analyse\s+rheumatology\s+presentation/i.test((b.textContent||'').trim()));}
function ensureHint(btn){let h=document.getElementById('analysisStateHint');if(!h){h=document.createElement('div');h.id='analysisStateHint';h.className='analysis-next-hint';h.setAttribute('aria-live','polite');btn.insertAdjacentElement('afterend',h)}return h}
function setReady(){const btn=findAnalyseButton();if(!btn)return;btn.classList.remove('analysis-state-done');btn.classList.add('analysis-state-ready');btn.dataset.analysisComplete='false';const h=ensureHint(btn);h.classList.remove('done');h.textContent='Step 1: analyse the case. The button will turn green when the current case has been analysed.'}
function setDone(){const btn=findAnalyseButton();if(!btn)return;btn.classList.remove('analysis-state-ready');btn.classList.add('analysis-state-done');btn.dataset.analysisComplete='true';const h=ensureHint(btn);h.classList.add('done');h.textContent='Analysis complete for the current case. Proceed to Results to review the ranked differential and work-up.'}
function init(){const btn=findAnalyseButton();if(!btn)return false;setReady();if(!btn.dataset.analysisStateBound){btn.dataset.analysisStateBound='1';btn.addEventListener('click',()=>{setTimeout(setDone,0)},false)}const caseBox=document.getElementById('caseText')||document.querySelector('textarea');if(caseBox&&!caseBox.dataset.analysisStateBound){caseBox.dataset.analysisStateBound='1';caseBox.addEventListener('input',()=>{if(btn.dataset.analysisComplete==='true')setReady()})}['age','sex'].forEach(id=>{const el=document.getElementById(id);if(el&&!el.dataset.analysisStateBound){el.dataset.analysisStateBound='1';el.addEventListener('change',()=>{if(btn.dataset.analysisComplete==='true')setReady()})}});return true}
let tries=0;const timer=setInterval(()=>{tries++;if(init()||tries>30)clearInterval(timer)},150);
})();