(function(){
'use strict';
const css=document.createElement('style');css.textContent=`
.v21-entry{margin:0 0 14px}.v21-entry #caseText{min-height:250px}.v21-imports{margin-top:14px;border-top:1px solid var(--line);padding-top:12px}.v21-imports details{border:1px solid var(--line);border-radius:13px;background:#f9fcfc;overflow:hidden;margin:9px 0}.v21-imports summary{list-style:none;cursor:pointer;padding:14px 15px;font-weight:850;color:var(--navy);display:flex;justify-content:space-between;gap:8px}.v21-imports summary::-webkit-details-marker{display:none}.v21-imports summary::after{content:'＋';color:var(--teal);font-size:20px}.v21-imports details[open] summary::after{content:'−'}.v21-import-body{padding:0 13px 13px}.v21-file{width:100%;padding:10px;border:1px solid var(--line);border-radius:10px;background:#fff}.v21-status{margin-top:8px;font-size:12px;color:var(--mute)}.v21-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.v21-actions .btn{width:auto}.v21-step{display:inline-block;padding:5px 8px;border-radius:999px;background:#eef7f6;color:var(--teal);font-size:11px;font-weight:850;margin-bottom:8px}@media(max-width:620px){.v21-entry #caseText{min-height:270px}}
`;document.head.appendChild(css);

function loadScript(src,test){return new Promise((res,rej)=>{if(test())return res();const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=()=>rej(new Error('Unable to load document reader'));document.head.appendChild(s)})}
async function pdfText(file){await loadScript('https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js',()=>!!window.pdfjsLib);pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let out=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),c=await p.getTextContent();out.push(c.items.map(x=>x.str).join(' '))}return out.join('\n\n')}
async function docxText(file){await loadScript('https://cdn.jsdelivr.net/npm/mammoth@1.8.0/mammoth.browser.min.js',()=>!!window.mammoth);return (await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()})).value}
function rtfPlain(s){return s.replace(/\\par[d]?/g,'\n').replace(/\\'[0-9a-fA-F]{2}/g,' ').replace(/\\[a-z]+-?\d* ?/g,'').replace(/[{}]/g,'').replace(/\n{3,}/g,'\n\n').trim()}
async function readClinicalFile(file){const n=file.name.toLowerCase();if(n.endsWith('.pdf'))return pdfText(file);if(n.endsWith('.docx'))return docxText(file);if(n.endsWith('.txt'))return file.text();if(n.endsWith('.rtf'))return rtfPlain(await file.text());if(n.endsWith('.doc'))throw new Error('Older .doc files cannot be reliably read in-browser. Please save as .docx or PDF first.');throw new Error('Unsupported file type. Use PDF, DOCX, TXT or RTF.')}

function install(){
 const box=document.getElementById('caseText'),screen=document.getElementById('input');if(!box||!screen||box.dataset.v21==='1')return;box.dataset.v21='1';
 const card=box.closest('.card')||box.parentElement;if(!card)return;
 const dictBtn=document.getElementById('dictateCaseBtn'),dictRow=dictBtn?.parentElement,dictNote=dictRow?.nextElementSibling,demographics=card.querySelector('.input-grid');
 const entry=document.createElement('section');entry.className='v21-entry';entry.innerHTML='<div class="v21-step">1 · ENTER / DICTATE CASE</div><div style="font-weight:850;color:var(--navy);margin-bottom:5px">Clinical details</div><div class="small" style="margin-bottom:9px">Type, paste or dictate the case here. Importing a letter, PDF, Word file or photograph is optional and appears underneath.</div>';
 entry.appendChild(box);if(dictRow)entry.appendChild(dictRow);if(dictNote&&dictNote!==demographics)entry.appendChild(dictNote);if(demographics)entry.appendChild(demographics);

 const imports=document.createElement('section');imports.className='v21-imports';imports.innerHTML=`<div class="v21-step">2 · OPTIONAL IMPORT</div><details id="v21DocPanel"><summary>Upload a letter / clinical file</summary><div class="v21-import-body"><div class="small">PDF, Word (.docx), text or RTF. Text is read into the clinical-details box for clinician review before analysis.</div><input id="v21ClinicalFile" class="v21-file" type="file" accept=".pdf,.docx,.doc,.txt,.rtf,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain,application/rtf"><div class="v21-actions"><button class="btn secondary" type="button" id="v21ReadFile">Read file into case</button></div><div id="v21FileStatus" class="v21-status"></div></div></details><details id="v21ImagePanel"><summary>Import image / take photo of letter</summary><div class="v21-import-body" id="v21ImageBody"></div></details>`;
 const existingTools=document.querySelector('.letter-tools');if(existingTools)imports.querySelector('#v21ImageBody').appendChild(existingTools);
 const oldPanel=card.querySelector('.input-import-panel');if(oldPanel)oldPanel.remove();
 const oldDivider=card.querySelector('.import-divider');if(oldDivider)oldDivider.remove();
 // Force the requested order regardless of the original template: entry first, imports immediately after.
 card.insertBefore(entry,card.firstChild);card.insertBefore(imports,entry.nextSibling);

 const imageInput=document.getElementById('letterImages');const fileLabel=document.querySelector('.file-label');if(fileLabel&&imageInput){fileLabel.textContent='Choose image(s) / take photo';fileLabel.appendChild(imageInput)}
 document.getElementById('v21ReadFile').addEventListener('click',async()=>{const f=document.getElementById('v21ClinicalFile').files[0],st=document.getElementById('v21FileStatus');if(!f){st.textContent='Choose a file first.';return}st.textContent='Reading '+f.name+'…';try{let txt=await readClinicalFile(f);if(typeof deidentifyClinicalText==='function')txt=deidentifyClinicalText(txt);txt=txt.trim();if(!txt)throw new Error('No readable text was extracted.');box.value=txt;box.dispatchEvent(new Event('input',{bubbles:true}));st.textContent='Loaded '+f.name+'. Review the extracted text before analysis.';box.scrollIntoView({behavior:'smooth',block:'center'});box.focus()}catch(e){st.textContent=e.message||String(e)}});
 const review=document.getElementById('ocrReviewWrap');if(review)new MutationObserver(()=>{if(!review.classList.contains('hidden'))document.getElementById('v21ImagePanel').open=true}).observe(review,{attributes:true,attributeFilter:['class']});
}
try{install();sourceDecks.push(['Input workflow v21','Clinical free-text/dictation is forced above all import controls. Optional image/photo and PDF/DOCX/TXT/RTF letter import appear below.']);renderSources()}catch(e){console.warn('v21',e)}
})();