(function(){
'use strict';
const css=document.createElement('style');css.textContent=`
.example-library{margin:10px 0 12px;border:1px solid var(--line);border-radius:14px;background:#f9fcfc;overflow:hidden}.example-library>summary{list-style:none;cursor:pointer;padding:13px 14px;font-weight:850;color:var(--navy);display:flex;justify-content:space-between;align-items:center;gap:10px}.example-library>summary::-webkit-details-marker{display:none}.example-library>summary:after{content:'＋';color:var(--teal);font-size:20px}.example-library[open]>summary:after{content:'−'}.example-library-body{padding:0 12px 13px}.example-library-help{font-size:12px;color:var(--mute);line-height:1.45;margin-bottom:10px}.example-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.example-grid label{font-size:11px;font-weight:800;color:var(--teal);text-transform:uppercase;letter-spacing:.03em}.example-grid select{width:100%;margin-top:4px}.example-preview{margin:10px 0 0;padding:10px;border:1px dashed var(--line);border-radius:10px;background:#fff;font-size:12px;color:var(--mute);line-height:1.4}.example-load{margin-top:10px}.example-badge{display:inline-block;padding:4px 7px;border-radius:999px;background:#eef7f6;color:var(--teal);font-size:11px;font-weight:800}@media(max-width:620px){.example-grid{grid-template-columns:1fr}.example-library-body{padding:0 10px 11px}}
`;document.head.appendChild(css);

const CASES={
 'Rheumatoid arthritis':[
  {n:'Classic seropositive small-joint RA',a:46,s:'Female',t:'46-year-old woman with 10 weeks of symmetrical MCP, PIP and wrist pain and swelling. Morning stiffness lasts about 2 hours and she struggles with jars and dressing. Examination documents synovitis at both wrists and multiple MCP/PIP joints; DIP joints are spared. CRP 38 mg/L, ESR 48 mm/h, RF positive and anti-CCP strongly positive. No psoriasis, dactylitis, recent infection or crystal history.'},
  {n:'Seronegative early inflammatory arthritis',a:39,s:'Male',t:'39-year-old man with 8 weeks of symmetrical wrist, MCP and MTP pain with prolonged morning stiffness and clinically documented swelling of both wrists and three MCP joints. CRP 22 mg/L. RF and anti-CCP are negative. No psoriasis, inflammatory bowel disease, preceding diarrhoea/urethritis, podagra or fever. Hand radiographs show no erosions.'},
  {n:'RA versus OA / pain amplification overlap',a:61,s:'Female',t:'61-year-old woman with known hand osteoarthritis and 3 months of worsening hand pain. She now reports 90 minutes of morning stiffness and new swelling of both wrists and MCP joints, but also longstanding DIP bony enlargement and widespread tenderness with poor sleep. CRP 18 mg/L, anti-CCP positive, RF negative. The question is whether inflammatory arthritis coexists with OA and pain amplification.'}
 ],
 'Psoriatic arthritis':[
  {n:'Peripheral PsA with dactylitis and nails',a:42,s:'Male',t:'42-year-old man with psoriasis and 6 weeks of asymmetric swelling of the right knee, left ankle and an entire swollen second toe. Heel pain is worst on first steps in the morning. Nail pitting and onycholysis are present. CRP 31 mg/L; RF and anti-CCP are negative. No recent GI/GU infection.'},
  {n:'PsA before obvious skin disease',a:36,s:'Female',t:'36-year-old woman with 4 months of inflammatory hand pain involving several DIP joints, one dactylitic finger and Achilles enthesitis. No obvious psoriasis is reported, but her father has psoriasis and examination finds subtle scalp scale and nail pitting. CRP mildly raised; RF negative.'},
  {n:'Axial / peripheral PsA phenotype',a:45,s:'Male',t:'45-year-old man with plaque psoriasis, chronic back pain beginning at age 33 with night pain and improvement on movement, plus intermittent knee synovitis and enthesitis. HLA-B27 negative. Pelvic radiograph is equivocal. No uveitis or recent infection.'}
 ],
 'Axial spondyloarthritis':[
  {n:'Classic inflammatory back pain',a:29,s:'Male',t:'29-year-old man with 18 months of insidious low back and alternating buttock pain beginning before age 30. Morning stiffness lasts 60 minutes, pain wakes him in the second half of the night and improves with exercise but not rest. He has previous acute anterior uveitis. CRP 16 mg/L and HLA-B27 positive. Pelvic x-ray is normal.'},
  {n:'Possible non-radiographic axSpA',a:34,s:'Female',t:'34-year-old woman with chronic back pain beginning at 28, morning stiffness 45 minutes, improvement with movement and intermittent heel enthesitis. HLA-B27 negative and CRP normal. No psoriasis or IBD. Pelvic x-ray is normal; MRI SI joints is pending.'},
  {n:'Mixed inflammatory and mechanical back pain',a:47,s:'Male',t:'47-year-old man with longstanding low back pain. There is morning stiffness and occasional night pain, but symptoms also worsen after lifting, prolonged sitting and certain activities. He now has a swollen painful knee and raised CRP. No uveitis, psoriasis or IBD. Consider axial SpA versus peripheral inflammatory arthritis with coexisting mechanical back pain.'}
 ],
 'Reactive arthritis':[
  {n:'Post-enteric lower-limb oligoarthritis',a:27,s:'Male',t:'27-year-old man develops a swollen right knee and left ankle 3 weeks after a self-limited diarrhoeal illness. He has Achilles enthesitis and conjunctival irritation. CRP is raised. RF/anti-CCP negative. Joint aspiration is inflammatory with no crystals; Gram stain negative and culture pending.'},
  {n:'Post-GU reactive arthritis',a:31,s:'Male',t:'31-year-old man with asymmetric knee and ankle arthritis, heel pain and dysuria beginning 2 weeks after a new sexual contact. There are painless oral ulcers and a recent episode of red eye. No psoriasis. Urine NAAT is pending; joint aspiration is required to exclude infection/crystals.'},
  {n:'Chronic ReA versus PsA / SpA',a:35,s:'Female',t:'35-year-old woman with recurrent asymmetric lower-limb oligoarthritis, enthesitis and back stiffness following a diarrhoeal illness 5 months ago. No current infection is evident. There is no psoriasis but one nail has pitting. HLA-B27 positive. The differential includes chronic reactive arthritis, PsA and peripheral/axial SpA.'}
 ],
 'Gout':[
  {n:'Classic podagra',a:52,s:'Male',t:'52-year-old man with abrupt onset overnight of severe first MTP pain, erythema and swelling, reaching maximum intensity within hours. He has CKD and takes a thiazide diuretic. Serum urate is 520 micromol/L. No fever. First episode; aspiration is considered because infection must still be excluded if clinically uncertain.'},
  {n:'Normal urate during acute flare',a:64,s:'Female',t:'64-year-old woman with an acutely hot swollen knee and severe pain. Serum urate during the flare is 310 micromol/L. CRP 72 mg/L. She has no previous gout diagnosis. Joint aspiration is planned for cell count, Gram stain/culture and crystals because normal serum urate does not exclude gout and septic arthritis remains a competing diagnosis.'},
  {n:'Chronic tophaceous gout',a:68,s:'Male',t:'68-year-old man with recurrent attacks in feet, ankles and knees over years, firm nodules at elbows and toes, CKD and persistent hyperuricaemia. He now has chronic hand and wrist discomfort. Consider chronic gout but distinguish from RA, CPPD and OA.'}
 ],
 'CPPD':[
  {n:'Acute CPP crystal arthritis',a:76,s:'Female',t:'76-year-old woman with abrupt painful swelling of the knee, warmth and reduced movement. CRP is raised and she is afebrile. X-ray shows chondrocalcinosis. Synovial fluid is planned for CPP crystals and culture because septic arthritis remains an important mimic.'},
  {n:'Chronic CPPD mimicking RA',a:72,s:'Male',t:'72-year-old man with chronic wrist and MCP swelling and stiffness. RF and anti-CCP are negative. Hand radiographs show chondrocalcinosis and an OA pattern involving atypical joints. Consider chronic CPP inflammatory arthritis versus seronegative RA.'},
  {n:'Young CPPD prompting metabolic work-up',a:49,s:'Female',t:'49-year-old woman with recurrent acute knee and wrist attacks and radiographic chondrocalcinosis. This is relatively young for CPPD. Consider haemochromatosis, hyperparathyroidism, hypomagnesaemia or other metabolic predisposition while confirming crystal disease.'}
 ],
 'Osteoarthritis':[
  {n:'Typical hand and knee OA',a:66,s:'Female',t:'66-year-old woman with years of activity-related knee and hand pain, morning stiffness under 15 minutes, crepitus and bony enlargement of DIP/PIP and first CMC joints. No objective synovitis or systemic symptoms. CRP normal.'},
  {n:'OA with inflammatory mimic concern',a:70,s:'Male',t:'70-year-old man with known knee OA but new prolonged morning stiffness and a clearly swollen wrist and knee. CRP is 54 mg/L. Existing OA may contribute to pain, but the new synovitis and inflammatory markers require consideration of CPPD, gout, RA or another inflammatory process.'},
  {n:'Mechanical hip OA pattern',a:59,s:'Female',t:'59-year-old woman with gradually progressive groin pain worse on walking, reduced hip internal rotation and brief stiffness after rest. No night sweats, inflammatory morning stiffness, peripheral joint swelling or systemic features.'}
 ],
 'Fibromyalgia':[
  {n:'Primary fibromyalgia phenotype',a:38,s:'Female',t:'38-year-old woman with 18 months of widespread pain, fatigue, non-restorative sleep and cognitive fog. Examination shows diffuse tenderness but no joint swelling, objective weakness or focal neurological deficit. FBC, CRP, TSH and CK are normal.'},
  {n:'Fibromyalgia coexisting with inflammatory arthritis',a:50,s:'Female',t:'50-year-old woman with established inflammatory arthritis and persistent widespread pain, fatigue and poor sleep despite little current objective synovitis and normal inflammatory markers. She has diffuse tenderness. The question is whether pain amplification coexists with controlled inflammatory disease.'},
  {n:'Fibromyalgia versus myopathy',a:43,s:'Male',t:'43-year-old man reports fatigue, aching and difficulty with stairs but formal examination shows normal proximal power. CK and CRP are normal. Sleep is poor and pain is widespread. Clarify true weakness versus pain/fatigue before labelling inflammatory myopathy.'}
 ],
 'Polymyalgia rheumatica':[
  {n:'Classic PMR',a:72,s:'Female',t:'72-year-old woman with 5 weeks of bilateral shoulder and hip-girdle aching, morning stiffness over 60 minutes and difficulty turning in bed, but no objective muscle weakness. ESR 68 mm/h and CRP 46 mg/L. No peripheral synovitis. No headache, jaw claudication or visual symptoms.'},
  {n:'PMR with GCA red-flag symptoms',a:76,s:'Male',t:'76-year-old man with new bilateral shoulder stiffness and raised CRP plus a new temporal headache and jaw fatigue when chewing. He reports transient visual blurring. This should trigger urgent GCA assessment rather than treating as uncomplicated PMR.'},
  {n:'PMR mimic: age under 50 with swollen knee',a:47,s:'Male',t:'47-year-old man with 6 weeks of bilateral shoulder pain and morning stiffness plus a clearly swollen painful knee. CRP 105 mg/L. Longstanding back pain has some morning stiffness but also activity-related exacerbation. PMR is strongly age-atypical; consider seronegative inflammatory arthritis/peripheral SpA, infection or crystal disease.'}
 ],
 'Systemic lupus erythematosus (SLE)':[
  {n:'Multisystem SLE',a:28,s:'Female',t:'28-year-old woman with photosensitive rash, oral ulcers, inflammatory hand arthritis, pleuritic chest pain and fatigue. FBC shows lymphopenia; urinalysis has protein and blood. ANA positive, anti-dsDNA positive and C3/C4 low. Assess renal involvement and alternative causes including infection.'},
  {n:'Possible lupus nephritis presentation',a:32,s:'Female',t:'32-year-old woman with ankle oedema, hypertension, arthralgia and fatigue. Urinalysis shows haematuria, proteinuria and active sediment; creatinine has risen. ANA and anti-dsDNA are positive with low complement. Urgent renal quantification and nephrology/rheumatology assessment are required; biopsy may be indicated.'},
  {n:'Positive ANA without sufficient SLE phenotype',a:41,s:'Female',t:'41-year-old woman with fatigue, widespread pain and dry mouth. ANA is positive at low titre, but there is no objective synovitis, cytopenia, nephritis, serositis or characteristic mucocutaneous disease. CRP, complements and urinalysis are normal. A positive ANA alone should not establish SLE.'}
 ],
 'Dermatomyositis':[
  {n:'Classic dermatomyositis',a:48,s:'Female',t:'48-year-old woman with 6 weeks of progressive symmetrical proximal weakness, difficulty rising from chairs and lifting arms, heliotrope rash and Gottron papules. CK 3200 U/L and AST/ALT elevated. She reports mild dysphagia. Assess myositis antibodies, MRI/EMG/biopsy as needed, ILD, cardiac involvement and malignancy risk.'},
  {n:'Amyopathic dermatomyositis / ILD concern',a:44,s:'Female',t:'44-year-old woman with Gottron papules, heliotrope-type rash and mechanic-like hand changes but no clear weakness and normal CK. She has new exertional dyspnoea and dry cough. Consider clinically amyopathic dermatomyositis with ILD; normal CK does not exclude this phenotype.'},
  {n:'Myositis mimic from statin',a:67,s:'Male',t:'67-year-old man with progressive proximal weakness and markedly raised CK while taking a statin. No dermatomyositis rash. Clarify drug exposure, anti-HMGCR/SRP where appropriate, thyroid/electrolytes, MRI/EMG and possible biopsy to distinguish toxic versus immune-mediated necrotising myopathy.'}
 ],
 'Giant cell arteritis':[
  {n:'Cranial GCA with visual threat',a:74,s:'Female',t:'74-year-old woman with new temporal headache, scalp tenderness, jaw claudication and transient monocular visual loss. ESR 92 mm/h, CRP 78 mg/L and platelets elevated. This is a time-critical GCA presentation; confirmatory imaging/biopsy must not delay treatment.'},
  {n:'Large-vessel GCA phenotype',a:69,s:'Female',t:'69-year-old woman with constitutional symptoms, raised CRP, bilateral arm claudication and an inter-arm blood-pressure difference without prominent headache. Consider extracranial large-vessel GCA and assess vascular imaging.'}
 ],
 'Granulomatosis with polyangiitis':[
  {n:'ENT-lung-renal GPA',a:51,s:'Male',t:'51-year-old man with months of sinusitis and nasal crusting, new haemoptysis and fatigue. Creatinine is rising; urinalysis shows blood, protein and red-cell casts. CT chest shows nodules. PR3-ANCA positive. Pulmonary-renal syndrome requires urgent escalation and tissue confirmation where feasible.'},
  {n:'Limited GPA versus infection',a:43,s:'Female',t:'43-year-old woman with persistent sinus/ear disease, episcleritis and pulmonary nodules but normal renal function. PR3-ANCA is negative. Consider limited GPA but actively exclude TB/fungal disease, malignancy and other mimics; ANCA negativity does not exclude disease.'}
 ],
 'Eosinophilic granulomatosis with polyangiitis':[
  {n:'Asthma-eosinophilia-neuropathy phenotype',a:49,s:'Female',t:'49-year-old woman with adult-onset asthma, chronic sinusitis, eosinophilia, purpura and new foot drop from suspected mononeuritis multiplex. Chest imaging shows patchy infiltrates. Consider EGPA; assess renal, cardiac and GI involvement and exclude secondary eosinophilia.'},
  {n:'EGPA with occult cardiac involvement concern',a:55,s:'Male',t:'55-year-old man with severe asthma, eosinophilia and systemic symptoms plus intermittent chest discomfort. ANCA is negative. Because ANCA can be absent and cardiac disease can be clinically silent, cardiac biomarkers/imaging should be considered alongside vasculitis assessment.'}
 ],
 'Takayasu arteritis':[
  {n:'Young woman with limb claudication',a:31,s:'Female',t:'31-year-old woman with fatigue, arm claudication, reduced left radial pulse, a 25 mmHg inter-arm blood-pressure difference and a subclavian bruit. CRP raised. Consider Takayasu arteritis and obtain vascular imaging such as CTA/MRA.'},
  {n:'Takayasu versus structural vascular disease',a:37,s:'Female',t:'37-year-old woman with hypertension, asymmetric pulses and episodic dizziness but only mildly raised inflammatory markers. Distinguish active large-vessel arteritis from structural damage or alternative vascular disease using vascular examination and imaging.'}
 ],
 'Polyarteritis nodosa':[
  {n:'Medium-vessel PAN phenotype',a:46,s:'Male',t:'46-year-old man with weight loss, livedo reticularis, painful asymmetric peripheral neuropathy, abdominal pain after meals and new hypertension. Urinalysis has no glomerular sediment and there is no pulmonary capillaritis. Consider PAN; assess hepatitis status and medium-vessel imaging/biopsy.'},
  {n:'PAN versus ANCA vasculitis',a:52,s:'Male',t:'52-year-old man with myalgia, skin nodules, neuropathic pain and renal hypertension. ANCA negative. No haemoptysis and no glomerulonephritis. The absence of pulmonary capillaritis/glomerulonephritis supports classic PAN over AAV.'}
 ],
 'Cryoglobulinaemic vasculitis':[
  {n:'HCV-associated mixed cryoglobulinaemia',a:58,s:'Female',t:'58-year-old woman with palpable purpura, arthralgia, neuropathic symptoms and proteinuria. C4 is low and RF positive. History includes hepatitis C. Obtain correctly handled cryoglobulins and assess renal, infectious and haematological causes.'},
  {n:'Cryoglobulinaemia versus SLE/Sjögren',a:63,s:'Female',t:'63-year-old woman with purpura, Raynaud symptoms, neuropathy and low C4. Cryoglobulin testing was initially negative but sample handling was uncertain. Consider repeat correctly handled testing and evaluate HCV, autoimmune disease and monoclonal processes.'}
 ],
 'Behçet syndrome':[
  {n:'Mucocutaneous-ocular Behçet phenotype',a:29,s:'Male',t:'29-year-old man with recurrent painful oral ulcers, recurrent genital ulcers, erythema-nodosum-like lesions and episodes of painful red eye diagnosed as uveitis. He also has intermittent inflammatory ankle arthritis. Consider Behçet syndrome and assess vascular/neurological/GI involvement.'},
  {n:'Behçet with vascular disease',a:34,s:'Male',t:'34-year-old man with recurrent oral/genital ulceration and a previous uveitis episode who now presents with unexplained deep venous thrombosis. Consider vascular Behçet disease while excluding alternative thrombophilia and infection.'}
 ],
 'Sarcoidosis':[
  {n:'Löfgren-like presentation',a:33,s:'Female',t:'33-year-old woman with acute bilateral ankle periarthritis, erythema nodosum, fever and bilateral hilar lymphadenopathy. Consider sarcoidosis/Löfgren syndrome but evaluate infectious and malignant mimics where appropriate.'},
  {n:'Multisystem sarcoid mimic',a:41,s:'Male',t:'41-year-old man with chronic cough, hilar adenopathy, uveitis and ankle arthralgia. Calcium is mildly elevated. Consider sarcoidosis while excluding TB, lymphoma and other granulomatous disease.'}
 ],
 'Adult-onset Still disease':[
  {n:'Classic systemic inflammatory phenotype',a:26,s:'Female',t:'26-year-old woman with daily spiking fevers, evanescent salmon-coloured rash, sore throat and inflammatory polyarthritis. CRP and ferritin are markedly elevated; RF and ANA negative. Infection and malignancy must be actively excluded.'},
  {n:'Still disease versus infection',a:35,s:'Male',t:'35-year-old man with high fevers, neutrophilic leukocytosis, arthralgia and very high ferritin but no clear rash. Blood cultures and infection evaluation are ongoing. AOSD remains a diagnosis requiring exclusion of infectious, malignant and alternative inflammatory causes.'}
 ],
 'Septic arthritis':[
  {n:'Hot swollen knee',a:67,s:'Male',t:'67-year-old man with acute severe knee pain, marked swelling, warmth and inability to bear weight. He is diabetic and has rigors, CRP 190 mg/L and leukocytosis. Urgent joint aspiration for cell count, Gram stain/culture and crystals plus blood cultures is required.'},
  {n:'Septic arthritis without fever',a:74,s:'Female',t:'74-year-old woman on immunosuppression with a rapidly swollen painful wrist and reduced movement but no fever. CRP elevated. Infection remains a must-not-miss diagnosis; absence of fever does not exclude septic arthritis.'}
 ],
 'Sjögren syndrome':[
  {n:'Sicca with systemic clues',a:52,s:'Female',t:'52-year-old woman with persistent dry eyes and dry mouth, parotid swelling, fatigue, arthralgia and peripheral neuropathic symptoms. ANA/SSA are positive. Assess objective sicca testing, systemic organ involvement and alternative causes of dryness.'},
  {n:'Dryness from medication versus Sjögren',a:64,s:'Female',t:'64-year-old woman reports dry mouth and gritty eyes but takes several anticholinergic medicines. There is no parotid swelling, inflammatory arthritis or systemic feature. Clarify objective gland dysfunction and serology before diagnosing Sjögren syndrome.'}
 ],
 'Systemic sclerosis':[
  {n:'Raynaud-sclerodactyly-ILD phenotype',a:45,s:'Female',t:'45-year-old woman with Raynaud phenomenon, puffy fingers progressing to sclerodactyly, digital pitting scars, reflux and exertional dyspnoea. Nailfold capillaries are abnormal. Assess SSc antibodies, ILD with PFT/HRCT and pulmonary hypertension/cardiac involvement.'},
  {n:'Renal-crisis red flag',a:53,s:'Female',t:'53-year-old woman with known diffuse systemic sclerosis develops abrupt severe hypertension, headache and rising creatinine. Scleroderma renal crisis is a medical emergency and should not be attributed to routine disease fluctuation.'}
 ],
 'Antisynthetase syndrome':[
  {n:'Myositis-ILD-arthritis phenotype',a:47,s:'Female',t:'47-year-old woman with proximal weakness, inflammatory hand arthritis, Raynaud phenomenon, mechanic’s hands and progressive dyspnoea. CK elevated and HRCT suggests ILD. Consider antisynthetase syndrome and obtain myositis-specific antibodies while assessing lung severity.'},
  {n:'ILD-dominant antisynthetase syndrome',a:56,s:'Male',t:'56-year-old man with progressive ILD, mechanic’s hands and inflammatory arthritis but minimal weakness and near-normal CK. Consider an antisynthetase phenotype; muscle enzymes may be normal when lung disease dominates.'}
 ]
};

function clean(s){return String(s||'').replace(/\s+/g,' ').trim().toLowerCase()}
function casesForModule(m){const lab=clean(m.label),entries=Object.entries(CASES);let x=entries.find(([k])=>clean(k)===lab);if(x)return x[1];x=entries.find(([k])=>lab.includes(clean(k))||clean(k).includes(lab));return x?x[1]:null}
function findLoadButton(){return Array.from(document.querySelectorAll('button,.btn')).find(b=>/load example case/i.test(b.textContent||''))}
function setField(id,selector,val){const e=document.getElementById(id)||document.querySelector(selector);if(!e)return;if(e.tagName==='SELECT'){const opt=[...e.options].find(o=>clean(o.value)===clean(val)||clean(o.textContent)===clean(val));if(opt)e.value=opt.value}else e.value=val;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))}
function populate(c){const box=document.getElementById('caseText');if(!box)return;box.value=c.t;box.dispatchEvent(new Event('input',{bubbles:true}));setField('age','input[type="number"]',c.a);setField('sex','select',c.s);const p=document.getElementById('examplePreview');if(p)p.innerHTML='<span class="example-badge">Loaded</span> '+c.n+' — edit any details before analysing.';box.scrollIntoView({behavior:'smooth',block:'center'})}
function install(){const old=findLoadButton();if(!old||document.getElementById('exampleCaseLibrary'))return;const supported=(typeof modules!=='undefined'?modules:[]).map(m=>({m,c:casesForModule(m)})).filter(x=>x.c&&x.c.length);if(!supported.length)return;const d=document.createElement('details');d.id='exampleCaseLibrary';d.className='example-library';d.innerHTML='<summary><span>Try a different example case <span class="example-badge">testing library</span></span></summary><div class="example-library-body"><div class="example-library-help">Source-based synthetic teaching cases for stress-testing diagnostic reasoning. Choose a diagnosis, then a classic, atypical or overlap/mimic scenario where available. These are fictional and contain no patient identifiers.</div><div class="example-grid"><label>Diagnosis<select id="exampleDx"></select></label><label>Scenario<select id="exampleScenario"></select></label></div><div id="examplePreview" class="example-preview">Select a diagnosis and scenario, then load it into the clinical-details box.</div><button type="button" class="btn secondary example-load" id="loadSelectedExample">Load selected example</button></div>';
 old.parentNode.insertBefore(d,old);const dx=d.querySelector('#exampleDx'),sc=d.querySelector('#exampleScenario');supported.sort((a,b)=>(a.m.label||'').localeCompare(b.m.label||''));supported.forEach((x,i)=>{const o=document.createElement('option');o.value=i;o.textContent=x.m.label;dx.appendChild(o)});function refresh(){sc.innerHTML='';supported[+dx.value].c.forEach((c,i)=>{const o=document.createElement('option');o.value=i;o.textContent=c.n;sc.appendChild(o)});const c=supported[+dx.value].c[0];d.querySelector('#examplePreview').textContent=c.t.slice(0,180)+(c.t.length>180?'…':'')}dx.onchange=refresh;sc.onchange=()=>{const c=supported[+dx.value].c[+sc.value];d.querySelector('#examplePreview').textContent=c.t.slice(0,180)+(c.t.length>180?'…':'')};d.querySelector('#loadSelectedExample').onclick=()=>populate(supported[+dx.value].c[+sc.value]);refresh();old.textContent='Load original example case';
}
const mo=new MutationObserver(()=>install());mo.observe(document.body,{subtree:true,childList:true});setTimeout(install,100);setTimeout(install,600);
try{sourceDecks.push(['Example case library v29','Adds multiple fictional source-based cases across supported diagnoses, including classic, atypical/seronegative, overlap and mimic scenarios for stress-testing phenotype, differential and work-up behaviour.']);renderSources()}catch(e){}
})();