(function(){
'use strict';
const css=document.createElement('style');css.textContent=`
/* v30 navigation + compact ranked differentials + investigation grouping */
.rdx-dx-accordion{margin:10px 0;border:1px solid var(--line);border-radius:14px;background:#fff;overflow:hidden}.rdx-dx-accordion>summary{list-style:none;cursor:pointer;padding:13px 14px;display:flex;gap:10px;align-items:flex-start}.rdx-dx-accordion>summary::-webkit-details-marker{display:none}.rdx-dx-accordion>summary:after{content:'＋';margin-left:auto;color:var(--teal);font-size:20px;font-weight:800}.rdx-dx-accordion[open]>summary:after{content:'−'}.rdx-dx-rank{display:grid;place-items:center;min-width:32px;height:32px;border-radius:50%;background:var(--teal);color:#fff;font-weight:850}.rdx-dx-summary-main{min-width:0;flex:1}.rdx-dx-title{font-weight:850;color:var(--navy);line-height:1.3}.rdx-dx-signal{font-size:12px;color:var(--teal);font-weight:750;margin-top:3px}.rdx-dx-body{padding:0 14px 14px}.rdx-dx-body ul{margin:6px 0 12px 20px;padding:0}.rdx-dx-body li{margin:5px 0;line-height:1.4}.rdx-dx-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.rdx-dx-actions .btn{width:auto!important;flex:1 1 210px}.rdx-module-back{position:sticky;top:6px;z-index:30;margin:0 0 10px;display:inline-flex;align-items:center;gap:6px;width:auto!important;background:#fff!important;box-shadow:0 2px 9px rgba(11,46,79,.12)}
.rdx-investigations{margin-top:12px}.rdx-investigation-intro{font-size:12px;color:var(--mute);line-height:1.45;margin-bottom:8px}.rdx-investigation-group{margin:8px 0;border:1px solid var(--line);border-radius:11px;overflow:hidden;background:#fbfdfd}.rdx-investigation-group>summary{list-style:none;cursor:pointer;padding:11px 12px;font-weight:800;color:var(--navy);display:flex;align-items:center;justify-content:space-between;gap:8px}.rdx-investigation-group>summary::-webkit-details-marker{display:none}.rdx-investigation-group>summary:after{content:'＋';color:var(--teal);font-size:18px}.rdx-investigation-group[open]>summary:after{content:'−'}.rdx-investigation-body{padding:0 10px 10px}.rdx-stage{display:inline-block;margin-left:6px;padding:2px 6px;border-radius:999px;background:#eef7f6;color:var(--teal);font-size:10px;font-weight:800}.rdx-investigation-body .test-link{margin:6px 0!important}
@media(max-width:620px){.rdx-dx-accordion>summary{padding:11px}.rdx-dx-body{padding:0 11px 11px}.rdx-dx-actions{display:block}.rdx-dx-actions .btn{width:100%!important;margin-top:7px}.rdx-module-back{top:4px}}
`;document.head.appendChild(css);
function esc(s){return typeof escapeHtml==='function'?escapeHtml(String(s||'')):String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function currentScreen(){for(const id of ['input','results','criteria','about']){const el=document.getElementById(id);if(el&&getComputedStyle(el).display!=='none'&&!el.classList.contains('hidden'))return id}return'results'}
function tabFor(id){const idx={input:0,results:1,criteria:2,about:3}[id]??1;return document.querySelectorAll('.tab')[idx]||null}
const oldOpenModule=window.openModule;
window.openModule=function(key){window.__rdxReturnScreen=currentScreen()==='criteria'?(window.__rdxReturnScreen||'results'):currentScreen();if(typeof oldOpenModule==='function')oldOpenModule(key);else if(typeof showScreen==='function')showScreen('criteria',tabFor('criteria'));setTimeout(()=>{ensureBack();const el=document.getElementById('module-'+key);if(el){el.open=true;const p=el.closest('.module-group');if(p)p.open=true;el.scrollIntoView({behavior:'smooth',block:'start'})}},80)};
function ensureBack(){const target=document.getElementById('criteriaCards');if(!target||document.getElementById('rdxModuleBack'))return;const b=document.createElement('button');b.id='rdxModuleBack';b.type='button';b.className='btn secondary rdx-module-back';b.textContent='← Back to previous page';b.onclick=()=>{const id=window.__rdxReturnScreen||'results';if(typeof showScreen==='function')showScreen(id,tabFor(id))};target.parentNode.insertBefore(b,target)}
function enhanceDifferentials(){const host=document.getElementById('differentials');if(!host)return;[...host.querySelectorAll('.card.dx[data-dx-key]')].forEach(card=>{if(card.dataset.v30Done)return;const key=card.dataset.dxKey;const rank=card.querySelector('.dx-rank-num')?.textContent?.trim()||'';const main=card.querySelector('.dx-rank-main');if(!main)return;const title=main.querySelector('h3')?.textContent?.trim()||modules.find(m=>m.key===key)?.label||'Differential diagnosis';const signal=main.querySelector('.like')?.textContent?.trim()||'';const clone=main.cloneNode(true);clone.querySelector('h3')?.remove();clone.querySelector('.like')?.remove();clone.querySelector('.dx-hint')?.remove();const d=document.createElement('details');d.className='rdx-dx-accordion';d.dataset.dxKey=key;d.innerHTML=`<summary><span class="rdx-dx-rank">${esc(rank)}</span><span class="rdx-dx-summary-main"><div class="rdx-dx-title">${esc(title)}</div><div class="rdx-dx-signal">${esc(signal)}</div></span></summary><div class="rdx-dx-body"></div>`;const body=d.querySelector('.rdx-dx-body');while(clone.firstChild)body.appendChild(clone.firstChild);const acts=document.createElement('div');acts.className='rdx-dx-actions';acts.innerHTML=`<button type="button" class="btn secondary">View full reasoning</button><button type="button" class="btn">Open full disease module</button>`;acts.children[0].onclick=e=>{e.stopPropagation();if(typeof showDifferentialDetail==='function')showDifferentialDetail(key)};acts.children[1].onclick=e=>{e.stopPropagation();openModule(key)};body.appendChild(acts);card.replaceWith(d)});}
function catFor(m){const g=((m.group||'')+' '+(m.label||'')).toLowerCase();if(/connective|lupus|sjö|sjog|scler|mixed connective|overlap syndrome|raynaud/.test(g))return'Connective tissue disease';if(/vascul|giant cell|gca|takayasu|polyangiitis|granulomatosis|behcet|cryoglob|pan\b/.test(g))return'Vasculitis';if(/myositis|dermatomy|polymyos|antisynthet|muscle/.test(g))return'Inflammatory myopathy';if(/spondy|psoriatic|reactive|rheumatoid|inflammatory arthritis|early arthritis|seronegative|adult-onset still|still disease/.test(g))return'Inflammatory arthritis & spondyloarthritis';if(/gout|cppd|crystal/.test(g))return'Crystal arthritis';if(/osteoarthritis|mechanical|soft-tissue|regional pain/.test(g))return'Mechanical / degenerative & regional pain';if(/fibromyalgia|nociplastic|fatigue|me\/cfs/.test(g))return'Widespread pain / nociplastic syndromes';if(/polymyalgia|pmr/.test(g))return'Polymyalgia rheumatica & related syndromes';if(/sarcoid/.test(g))return'Sarcoidosis & multisystem mimics';return'Other rheumatology / mimics'}
const order=['Inflammatory arthritis & spondyloarthritis','Connective tissue disease','Vasculitis','Inflammatory myopathy','Crystal arthritis','Polymyalgia rheumatica & related syndromes','Mechanical / degenerative & regional pain','Widespread pain / nociplastic syndromes','Sarcoidosis & multisystem mimics','Other rheumatology / mimics'];
function bullets(a,n){return(a||[]).filter(Boolean).slice(0,n||8).map(x=>`<li>${esc(x)}</li>`).join('')}
function classifyTest(t){const x=String(t||'').toLowerCase();if(/history|examin|joint count|skin|nail|enthes|muscle power|blood pressure|pulse|schirmer|ocular|salivary flow|orthostatic|pathergy/.test(x))return'Bedside & examination';if(/aspirat|arthrocent|synovial|point.of.care|gram stain/.test(x))return'Point-of-care & procedures';if(/urinal|urine|culture|naat|pcr|stool|blood culture|hepatitis|hiv|infection/.test(x))return'Urine & microbiology';if(/x-ray|radiograph|ultrasound|\bus\b|mri|ct |hrct|pet|cta|mra|dect|imaging/.test(x))return'Imaging / radiology';if(/pft|dlco|ecg|echo|echocardi|troponin|nt-probnp|cardiac|lung function/.test(x))return'Physiology / organ assessment';if(/biopsy|histolog|tissue|emg/.test(x))return'Tissue / specialised tests';if(/fbc|cbc|esr|crp|rf|ccp|ana|anca|antibody|complement|c3|c4|ck|aldolase|ferritin|urate|calcium|magnesium|phosphate|alp|pth|iron|tsh|renal|liver|creatin|eosinoph|ige|immunoglob|spep|blood/.test(x))return'Bloods & immunology';return'Other / conditional investigations'}
function groupedTests(m){const v=m.v15||{},arr=[];const add=(xs,stage)=>{(xs||[]).forEach(t=>{const s=String(t||'').trim();if(s)arr.push({t:s,stage})})};add(v.first,'First-line');add(v.conditional,'Conditional');add(m.tests,'Additional');const seen=new Set(),groups={};for(const it of arr){const k=it.t.toLowerCase().replace(/\s+/g,' ');if(seen.has(k))continue;seen.add(k);const c=classifyTest(it.t);(groups[c]||(groups[c]=[])).push(it)}return groups}
function testButton(it){const q=JSON.stringify(it.t).replace(/'/g,'&#39;');return `<button type="button" class="test-link" onclick='showTestEvidence(${q})'><b>${esc(it.t)}</b><span class="rdx-stage">${esc(it.stage)}</span><br><span class="tiny">Tap for test performance and interpretation caveats where available</span></button>`}
window.renderCriteria=function(){const target=document.getElementById('criteriaCards');if(!target)return;const usable=modules.filter(m=>m.key!=='urgent'),groups={};usable.forEach(m=>{const c=catFor(m);(groups[c]||(groups[c]=[])).push(m)});let html='<div class="module-nav-intro small"><b>Browse by disease family.</b> Expand a disease family, then a condition. Investigations are deduplicated and grouped by type to reduce repetition.</div>';for(const c of order){const list=groups[c]||[];if(!list.length)continue;html+=`<details class="module-group"><summary><span>${esc(c)}</span><span class="module-count">${list.length} modules</span></summary><div class="module-group-body">`;list.sort((a,b)=>(a.label||'').localeCompare(b.label||''));for(const m of list){const v=m.v15||{},pattern=v.pattern||((m.support||[])[0]||''),mimics=m.mimics||v.mimics||[];html+=`<details class="condition-item" id="module-${m.key}"><summary><span><span class="module-chip">${esc(m.group||c)}</span>${esc(m.label)}</span></summary><div class="condition-body">`;if(pattern)html+=`<div class="condition-section">Diagnostic pattern</div><ul><li>${esc(pattern)}</li></ul>`;if((m.support||[]).length)html+=`<div class="condition-section">Features supporting</div><ul>${bullets((m.support||[]).filter(x=>x!==pattern),6)}</ul>`;if((m.against||[]).length)html+=`<div class="condition-section">Features against / guardrails</div><ul>${bullets(m.against,6)}</ul>`;if(mimics.length)html+=`<div class="condition-section">Important mimics</div><ul>${bullets(mimics,7)}</ul>`;if((m.missing||[]).length)html+=`<div class="condition-section">Key questions / missing information</div><ul>${bullets(m.missing,7)}</ul>`;html+=`<div class="condition-section">Classification / diagnostic framework</div><ul><li>${esc(m.criteria||'Classification criteria support standardisation but are not synonymous with diagnosis.')}</li></ul>`;const gt=groupedTests(m),cats=['Bedside & examination','Point-of-care & procedures','Bloods & immunology','Urine & microbiology','Imaging / radiology','Physiology / organ assessment','Tissue / specialised tests','Other / conditional investigations'].filter(x=>gt[x]?.length);if(cats.length){html+='<div class="condition-section">Investigations</div><div class="rdx-investigations"><div class="rdx-investigation-intro">Tests are grouped by practical type. First-line, conditional and additional entries are deduplicated within this module.</div>';for(const x of cats)html+=`<details class="rdx-investigation-group"><summary><span>${esc(x)}</span><span class="module-count">${gt[x].length}</span></summary><div class="rdx-investigation-body">${gt[x].map(testButton).join('')}</div></details>`;html+='</div>'}html+='</div></details>'}html+='</div></details>'}target.innerHTML=html;ensureBack()};
const mo=new MutationObserver(()=>{enhanceDifferentials();ensureBack()});mo.observe(document.body,{subtree:true,childList:true});setTimeout(()=>{try{renderCriteria()}catch(e){}enhanceDifferentials();ensureBack()},150);
try{sourceDecks.push(['Navigation and investigations v30','Ranked differentials are collapsible, each has direct full-reasoning and disease-module actions, disease modules have return navigation, and investigations are deduplicated and grouped into bedside/examination, procedures, bloods, microbiology, imaging, physiology, tissue and other categories.']);renderSources()}catch(e){console.warn('v30 patch',e)}
})();