(function(){
'use strict';
const css=document.createElement('style');css.textContent=`
/* v31 suggested work-up grouping */
.rdx-workup-intro{font-size:12px;line-height:1.45;color:var(--mute);margin:0 0 10px}.rdx-workup-group{margin:8px 0;border:1px solid var(--line);border-radius:12px;background:#fbfdfd;overflow:hidden}.rdx-workup-group>summary{list-style:none;cursor:pointer;padding:11px 12px;font-weight:800;color:var(--navy);display:flex;align-items:center;gap:8px}.rdx-workup-group>summary::-webkit-details-marker{display:none}.rdx-workup-group>summary:after{content:'＋';margin-left:auto;color:var(--teal);font-size:18px}.rdx-workup-group[open]>summary:after{content:'−'}.rdx-workup-group-body{padding:0 11px 11px}.rdx-workup-item{padding:8px 0;border-top:1px solid rgba(11,46,79,.08);line-height:1.4}.rdx-workup-item:first-child{border-top:0}.rdx-workup-source{display:inline-block;margin-left:6px;padding:2px 6px;border-radius:999px;background:#eef7f6;color:var(--teal);font-size:10px;font-weight:800}.rdx-workup-legacy{display:none!important}.rdx-workup-empty{font-size:12px;color:var(--mute);padding:8px 0}
@media(max-width:620px){.rdx-workup-group>summary{padding:10px}.rdx-workup-group-body{padding:0 10px 10px}.rdx-workup-intro{font-size:11.5px}}
`;document.head.appendChild(css);
function txt(el){return String(el?.textContent||'').replace(/\s+/g,' ').trim()}
function normalise(s){return String(s||'').toLowerCase().replace(/test \/ investigation:|tap for.*$/g,'').replace(/[•·:;,.()\[\]]/g,' ').replace(/\s+/g,' ').trim()}
function classify(s){const x=String(s||'').toLowerCase();
 if(/history|examin|joint count|skin|nail|enthes|dactyl|muscle power|blood pressure|pulse|range of motion|tender|swollen joint|neurolog|cardiorespiratory|abdomen|eye exam/.test(x))return'Bedside & examination';
 if(/aspirat|arthrocent|synovial|gram stain|point.of.care|urine dip|bedside ultrasound/.test(x))return'Point-of-care & procedures';
 if(/fbc|cbc|esr|crp|rf|ccp|ana|anca|antibody|complement|c3|c4|ck|aldolase|ferritin|urate|calcium|magnesium|phosphate|alp|pth|iron|tsh|renal|liver|creatin|eosinoph|ige|immunoglob|spep|blood test|bloods|hla-b27/.test(x))return'Bloods & immunology';
 if(/urinal|urine|culture|naat|pcr|stool|blood culture|hepatitis|hiv|microbiolog|infection screen/.test(x))return'Urine & microbiology';
 if(/x-ray|xray|radiograph|ultrasound|\bus\b|mri|ct |hrct|pet|cta|mra|dect|imaging|capillaroscopy/.test(x))return'Imaging / radiology';
 if(/pft|dlco|ecg|echo|echocardi|troponin|nt-probnp|cardiac|lung function|spirom|physiology/.test(x))return'Physiology / organ assessment';
 if(/biopsy|histolog|tissue|emg|nerve conduction|bone marrow/.test(x))return'Tissue / specialised tests';
 return'Other / conditional investigations'}
function findHeading(){const root=document.getElementById('results')||document.body;const els=[...root.querySelectorAll('h1,h2,h3,h4,.section-title,.minihead,div')];return els.find(el=>{const t=txt(el).toLowerCase();return (t==='suggested work-up'||t==='suggested workup'||t==='work-up'||t==='workup')&&el.children.length<4})}
function findCard(h){if(!h)return null;let n=h.nextElementSibling;for(let i=0;i<5&&n;i++,n=n.nextElementSibling){if(n.classList?.contains('card'))return n;const c=n.querySelector?.('.card');if(c)return c}return h.closest('.card')}
function candidateNodes(card){const out=[];const seen=new Set();const selectors=['button.test-link','button','li','.test-link','.investigation-item','.workup-item'];for(const sel of selectors){for(const el of card.querySelectorAll(sel)){if(el.closest('#rdxSuggestedWorkupGrouped'))continue;const t=txt(el);if(t.length<3||t.length>500)continue;if(/^(suggested work|investigations?|why|red flag|clinical summary)/i.test(t))continue;const k=normalise(t);if(!k||seen.has(el))continue;seen.add(el);out.push(el)}}return out}
function sourceTag(el){const t=txt(el).toLowerCase();if(/urgent|time-sensitive|red flag/.test(t))return'Urgent';if(/conditional|second-line|if |when |consider/.test(t))return'Conditional';if(/first-line|initial|baseline|core/.test(t))return'First-line';return''}
function rebuild(){const h=findHeading();const card=findCard(h);if(!h||!card)return;const old=document.getElementById('rdxSuggestedWorkupGrouped');if(old)old.remove();const nodes=candidateNodes(card);if(!nodes.length)return;const unique=new Map();for(const el of nodes){const raw=txt(el).replace(/Click for sensitivity, specificity and interpretation caveats/ig,'').replace(/Tap for test performance and interpretation caveats where available/ig,'').trim();const k=normalise(raw);if(!k)continue;if(!unique.has(k))unique.set(k,{text:raw,cat:classify(raw),stage:sourceTag(el),click:el.tagName==='BUTTON'?el.getAttribute('onclick'):null});el.classList.add('rdx-workup-legacy')}
 const groups={};for(const it of unique.values())(groups[it.cat]||(groups[it.cat]=[])).push(it);const order=['Bedside & examination','Point-of-care & procedures','Bloods & immunology','Urine & microbiology','Imaging / radiology','Physiology / organ assessment','Tissue / specialised tests','Other / conditional investigations'];const wrap=document.createElement('div');wrap.id='rdxSuggestedWorkupGrouped';wrap.innerHTML='<div class="rdx-workup-intro"><b>Suggested work-up:</b> investigations are deduplicated and grouped by practical type. Expand only the categories you need. Urgent and conditional items remain labelled where identifiable.</div>';
 for(const cat of order){const a=groups[cat]||[];if(!a.length)continue;const d=document.createElement('details');d.className='rdx-workup-group';if(cat==='Bedside & examination'||cat==='Bloods & immunology')d.open=true;d.innerHTML=`<summary><span>${cat}</span><span class="module-count">${a.length}</span></summary><div class="rdx-workup-group-body"></div>`;const body=d.querySelector('.rdx-workup-group-body');for(const it of a){const row=document.createElement(it.click?'button':'div');if(it.click){row.type='button';row.className='test-link rdx-workup-item';row.setAttribute('onclick',it.click)}else row.className='rdx-workup-item';row.innerHTML=`<b>${typeof escapeHtml==='function'?escapeHtml(it.text):it.text}</b>${it.stage?`<span class="rdx-workup-source">${it.stage}</span>`:''}`;body.appendChild(row)}wrap.appendChild(d)}
 card.insertBefore(wrap,card.firstChild)}
let timer;const mo=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(rebuild,100)});mo.observe(document.body,{subtree:true,childList:true,characterData:true});setTimeout(rebuild,180);setTimeout(rebuild,700);setTimeout(rebuild,1500);
try{sourceDecks.push(['Suggested work-up grouping v31','Suggested work-up is deduplicated and reorganised into collapsible bedside/examination, procedures, bloods, microbiology, imaging, physiology, tissue and other categories to reduce repetition and improve clinical flow.']);renderSources()}catch(e){console.warn('v31 work-up grouping',e)}
})();