(function(){
'use strict';
const css=document.createElement('style');css.textContent=`
/* v32 authoritative suggested work-up grouping */
#rdxWorkupV32{margin:0}.rdx32-note{font-size:12px;line-height:1.45;color:var(--mute);margin:0 0 10px}.rdx32-group{margin:9px 0;border:1px solid var(--line);border-radius:12px;overflow:hidden;background:#fbfdfd}.rdx32-group>summary{list-style:none;cursor:pointer;padding:12px;font-weight:850;color:var(--navy);display:flex;align-items:center;gap:8px}.rdx32-group>summary::-webkit-details-marker{display:none}.rdx32-group>summary:after{content:'＋';margin-left:auto;color:var(--teal);font-size:18px}.rdx32-group[open]>summary:after{content:'−'}.rdx32-body{padding:0 10px 10px}.rdx32-item{width:100%;text-align:left;margin:6px 0!important}.rdx32-count{font-size:11px;color:var(--mute);font-weight:700}.rdx32-hidden{display:none!important}
@media(max-width:620px){.rdx32-group>summary{padding:10px}.rdx32-note{font-size:11.5px}}
`;document.head.appendChild(css);
function clean(s){return String(s||'').replace(/Click for sensitivity, specificity and interpretation caveats/ig,'').replace(/Tap for test performance and interpretation caveats where available/ig,'').replace(/^Test\s*\/\s*investigation:\s*/i,'').replace(/\s+/g,' ').trim()}
function canon(s){return clean(s).toLowerCase().replace(/\band\b/g,'&').replace(/[;,:.()\[\]]/g,' ').replace(/\s+/g,' ').trim()}
function classOf(s){const x=s.toLowerCase();if(/examin|joint count|skin|nail|enthes|dactyl|muscle power|blood pressure|pulse|range of motion|tender|swollen joint|neurolog|cardiorespiratory|abdomen|eye exam/.test(x))return'Examination & bedside';if(/aspirat|arthrocent|synovial|gram stain|point.of.care|urine dip|bedside ultrasound/.test(x))return'Point-of-care & procedures';if(/urinal|urine |urine$|culture|naat|pcr|stool|blood culture|microbiolog/.test(x))return'Urine & microbiology';if(/x-ray|xray|radiograph|ultrasound|\bus\b|mri|ct\b|hrct|pet|cta|mra|dect|imaging|capillaroscopy/.test(x))return'Radiology / imaging';if(/pft|dlco|ecg|echo|echocardi|troponin|nt-probnp|lung function|spirom/.test(x))return'Physiology / organ assessment';if(/biopsy|histolog|tissue|emg|nerve conduction|bone marrow/.test(x))return'Tissue / specialised investigations';if(/fbc|cbc|esr|crp|rf|ccp|ana|ena|anca|antibod|complement|c3|c4|ck|aldolase|ferritin|urate|calcium|magnesium|phosphate|alp|pth|iron|tsh|renal|liver|creatin|eosinoph|ige|immunoglob|spep|hla-b27|blood/.test(x))return'Blood tests & immunology';return'Other investigations'}
function mergeable(a,b){if(a===b)return true;const aa=a.replace(/\b(panel|profile|screen|testing|tests|test)\b/g,'').trim(),bb=b.replace(/\b(panel|profile|screen|testing|tests|test)\b/g,'').trim();if(aa===bb)return true;const short=aa.length<bb.length?aa:bb,long=aa.length<bb.length?bb:aa;return short.length>8&&long.includes(short)}
function heading(){const r=document.getElementById('results')||document;return [...r.querySelectorAll('h1,h2,h3,h4,.section-title,.minihead,div')].find(e=>/^(suggested work-up|suggested workup)$/i.test(String(e.textContent||'').trim()))}
function cardAfter(h){if(!h)return null;let n=h.nextElementSibling;while(n){if(n.classList?.contains('card'))return n;if(n.querySelector?.('.card'))return n.querySelector('.card');n=n.nextElementSibling}return null}
function rebuild(){const h=heading(),card=cardAfter(h);if(!h||!card)return;const buttons=[...card.querySelectorAll('button.test-link')].filter(b=>!b.closest('#rdxWorkupV32'));if(!buttons.length)return;const items=[];for(const b of buttons){const t=clean(b.textContent);if(!t)continue;const c=canon(t);let old=items.find(x=>mergeable(x.c,c));if(old){if(t.length<old.t.length)old.t=t;continue}items.push({t,c,cat:classOf(t),onclick:b.getAttribute('onclick')||''})}
 buttons.forEach(b=>b.classList.add('rdx32-hidden'));const prior=document.getElementById('rdxSuggestedWorkupGrouped');if(prior)prior.classList.add('rdx32-hidden');let wrap=document.getElementById('rdxWorkupV32');if(wrap)wrap.remove();wrap=document.createElement('div');wrap.id='rdxWorkupV32';wrap.innerHTML='<div class="rdx32-note"><b>Suggested work-up:</b> repeated or near-duplicate recommendations have been consolidated. Tests are grouped by practical type; expand a category to review its investigations.</div>';
 const order=['Examination & bedside','Point-of-care & procedures','Blood tests & immunology','Urine & microbiology','Radiology / imaging','Physiology / organ assessment','Tissue / specialised investigations','Other investigations'];for(const cat of order){const arr=items.filter(x=>x.cat===cat);if(!arr.length)continue;const d=document.createElement('details');d.className='rdx32-group';d.innerHTML=`<summary><span>${cat}</span><span class="rdx32-count">${arr.length}</span></summary><div class="rdx32-body"></div>`;const body=d.querySelector('.rdx32-body');for(const it of arr){const b=document.createElement('button');b.type='button';b.className='test-link rdx32-item';b.innerHTML='<b>'+((typeof escapeHtml==='function')?escapeHtml(it.t):it.t)+'</b><br><span class="tiny">Tap for sensitivity, specificity and interpretation caveats where available</span>';if(it.onclick)b.setAttribute('onclick',it.onclick);body.appendChild(b)}wrap.appendChild(d)}card.insertBefore(wrap,card.firstChild)}
let t;const mo=new MutationObserver(()=>{clearTimeout(t);t=setTimeout(rebuild,120)});mo.observe(document.body,{subtree:true,childList:true,characterData:true});setTimeout(rebuild,250);setTimeout(rebuild,900);setTimeout(rebuild,1800);
try{sourceDecks.push(['Suggested work-up grouping v32','Authoritative Results-page work-up rebuild: near-duplicate tests are consolidated and recommendations are grouped into collapsible examination/bedside, procedures, bloods, urine/microbiology, imaging, physiology, tissue/specialised and other categories.']);renderSources()}catch(e){}
})();