(function(){
'use strict';
const css=document.createElement('style');css.textContent=`
.rdx34-missing{outline:3px solid #d99a19!important;outline-offset:2px;background:#fff8e7!important}.rdx34-note{font-size:12px;line-height:1.4;margin-top:7px;color:var(--mute)}.rdx34-note.warn{color:#9a5b00;font-weight:750}.rdx34-note.ok{color:#14745f}.rdx34-auto{font-size:11px;font-weight:800;color:var(--teal);margin-left:6px}
`;document.head.appendChild(css);
function els(){const text=document.getElementById('caseText');const grid=text?.closest('.card')?.querySelector('.input-grid')||document.querySelector('#input .input-grid');const controls=grid?[...grid.querySelectorAll('input,select')]:[];let age=controls.find(x=>x.type==='number'||/age/i.test((x.id||'')+' '+(x.name||'')+' '+(x.previousElementSibling?.textContent||'')));let sex=controls.find(x=>/sex|gender/i.test((x.id||'')+' '+(x.name||'')+' '+(x.previousElementSibling?.textContent||'')));if(!age&&controls[0])age=controls[0];if(!sex&&controls[1])sex=controls[1];const analyse=[...document.querySelectorAll('#input button, #input input[type=button], #input input[type=submit]')].find(b=>/analyse rheumatology presentation|analy[sz]e/i.test(b.textContent||b.value||''));return{text,grid,age,sex,analyse}}
function parse(t){t=String(t||'');let age=null,sex=null;const pats=[/\b(\d{1,3})\s*[- ]?year[- ]old\s+(male|female|man|woman|gentleman|lady)\b/i,/\b(\d{1,3})\s*(?:yo|y\/o|yr old|yrs old)\s*(male|female|man|woman|m|f)\b/i,/\b(\d{1,3})\s*[- ]?year[- ]old\b/i,/\bage(?:d)?\s*[:\-]?\s*(\d{1,3})\b/i];for(const p of pats){const m=t.match(p);if(m){const n=+m[1];if(n>=1&&n<=120){age=n;if(m[2])sex=m[2];break}}}if(!sex){const m=t.match(/\b(male|female|gentleman|lady|man|woman)\b/i);if(m)sex=m[1]}if(sex)sex=/female|woman|lady|\bf\b/i.test(sex)?'Female':'Male';return{age,sex}}
function setSex(el,val){if(!el||!val)return false;if(el.tagName==='SELECT'){const o=[...el.options].find(o=>new RegExp('^'+val,'i').test(o.text)||new RegExp('^'+val[0]+'$','i').test(o.value));if(o){el.value=o.value;el.dispatchEvent(new Event('change',{bubbles:true}));return true}}else{el.value=val;el.dispatchEvent(new Event('input',{bubbles:true}));return true}return false}
function note(grid){let n=document.getElementById('rdx34DemoNote');if(!n&&grid){n=document.createElement('div');n.id='rdx34DemoNote';n.className='rdx34-note';grid.insertAdjacentElement('afterend',n)}return n}
function validate(show){const{text,grid,age,sex,analyse}=els();if(!text||!age||!sex)return true;const p=parse(text.value);if(!age.value&&p.age){age.value=p.age;age.dataset.rdxAuto='1';age.dispatchEvent(new Event('input',{bubbles:true}))}if((!sex.value||/select|unknown|not specified/i.test(sex.value))&&p.sex){if(setSex(sex,p.sex))sex.dataset.rdxAuto='1'}const ageOK=!!String(age.value||'').trim(),sexOK=!!String(sex.value||'').trim()&&!/select|unknown|not specified/i.test(sex.value);age.classList.toggle('rdx34-missing',show&&!ageOK);sex.classList.toggle('rdx34-missing',show&&!sexOK);const n=note(grid);if(n){if(ageOK&&sexOK){n.className='rdx34-note ok';n.textContent=(age.dataset.rdxAuto==='1'||sex.dataset.rdxAuto==='1')?'Age/sex detected from the case text. Please verify before analysis.':''}else{n.className='rdx34-note'+(show?' warn':'');n.textContent='Age and sex are required for analysis. If they are stated in the case text they will be filled automatically; otherwise enter them manually.'}}if(analyse){analyse.setAttribute('aria-disabled',(!ageOK||!sexOK)?'true':'false');analyse.title=(!ageOK||!sexOK)?'Enter patient age and sex before analysis':''}return ageOK&&sexOK}
function bind(){const{text,age,sex,analyse}=els();if(!text||text.dataset.rdx34==='1')return;text.dataset.rdx34='1';let tm;text.addEventListener('input',()=>{clearTimeout(tm);tm=setTimeout(()=>validate(false),250)});text.addEventListener('change',()=>validate(false));[age,sex].filter(Boolean).forEach(e=>e.addEventListener('change',()=>{e.dataset.rdxAuto='0';validate(false)}));if(analyse)analyse.addEventListener('click',function(e){if(!validate(true)){e.preventDefault();e.stopImmediatePropagation();const x=!String(age.value||'').trim()?age:sex;x.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>x.focus(),250)}},true);validate(false)}
let tm;new MutationObserver(()=>{clearTimeout(tm);tm=setTimeout(bind,120)}).observe(document.body,{subtree:true,childList:true});setTimeout(bind,250);setTimeout(bind,1000);
try{sourceDecks.push(['Demographics workflow v34','Age and sex are automatically extracted from case text where explicitly stated, require clinician verification, and analysis is blocked with highlighted fields when either demographic is missing.']);renderSources()}catch(e){}
})();