(function(){
'use strict';
const css=document.createElement('style');css.textContent=`
/* v36 case review improvements */
.rdx36-review.good{border-left:5px solid #2e7d5b;background:#f2faf6}.rdx36-review.bad{border-left:5px solid #b3261e;background:#fff5f4}.rdx36-status{font-weight:900;margin-bottom:6px;display:flex;align-items:center;gap:7px}.rdx36-status.good{color:#23704f}.rdx36-status.bad{color:#a32638}.rdx36-filterbar{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.rdx36-filterbar button{border:1px solid var(--line);background:#fff;color:var(--navy);border-radius:999px;padding:8px 11px;font-size:12px;font-weight:800}.rdx36-filterbar button.active{background:var(--navy);color:#fff}.rdx36-dxbtn{width:100%;margin:10px 0;border:1.5px solid var(--teal);background:#f7fbfb;color:var(--navy);border-radius:11px;padding:12px;font-weight:850;text-align:left}.rdx36-reason{border:1px solid var(--line);border-radius:13px;background:#fff;margin:12px 0;padding:13px}.rdx36-reason h3{margin:0 0 8px;color:var(--navy);font-size:16px}.rdx36-for,.rdx36-against{border-radius:10px;padding:10px 11px;margin:8px 0}.rdx36-for{background:#edf8f2}.rdx36-against{background:#fff7e8}.rdx36-for b{color:#23704f}.rdx36-against b{color:#8a5a17}.rdx36-reason ul{margin:7px 0 0 18px;padding:0}.rdx36-reason li{margin:4px 0;line-height:1.4}.rdx36-modulelink{width:100%;border:0;border-radius:10px;background:var(--teal);color:#fff;padding:11px;font-weight:850;margin-top:8px}.rdx36-backcase{width:100%;border:1.5px solid var(--teal);background:#fff;color:var(--teal);border-radius:10px;padding:10px 12px;font-weight:850;margin:0 0 12px}.rdx36-hide{display:none!important}
`;document.head.appendChild(css);

let returnToCase=false;
let lastSummaryScroll=0;

function clean(s){return String(s||'').replace(/\s+/g,' ').trim()}
function esc(s){return (typeof escapeHtml==='function')?escapeHtml(String(s||'')):String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function summaryRoot(){const cases=document.getElementById('cases');if(!cases)return null;const score=cases.querySelector('.rdx-summary-score');if(!score)return null;return score.closest('.card')||score.parentElement?.parentElement||cases}
function currentTitle(){const cases=document.getElementById('cases');if(!cases)return'';const banners=[...cases.querySelectorAll('.rdx-case-banner')];for(let i=banners.length-1;i>=0;i--){const t=clean(banners[i].querySelector('h1,h2,h3,.rdx-case-title,strong,b')?.textContent||'');if(t&&t.toLowerCase()!=='case')return t}const heads=[...cases.querySelectorAll('h1,h2,h3,.rdx-case-title')].map(e=>clean(e.textContent)).filter(Boolean);return heads.find(t=>!/cases|performance|summary/i.test(t))||''}
function currentVignette(){const cases=document.getElementById('cases');if(!cases)return'';const v=[...cases.querySelectorAll('.rdx-case-vignette')].map(e=>clean(e.textContent)).filter(x=>x.length>40);return v[0]||''}
function moduleKeyFor(title){const t=title.toLowerCase();const map=[
[/rheumatoid|palindromic/,'ra'],[/psoriatic/,'psa'],[/axial spondy|ankylosing/,'axspa'],[/reactive/,'reactive'],[/gout/,'gout'],[/cpp|calcium pyrophosphate/,'cppd'],[/osteoarthritis/,'oa'],[/fibromyalgia|nociplastic/,'fibro'],[/polymyalgia/,'pmr'],[/giant cell|gca/,'gca'],[/systemic lupus|lupus/,'sle'],[/sj[oö]gren/,'sjogren'],[/systemic sclerosis|scleroderma/,'ssc'],[/dermatomyositis/,'dermatomyositis'],[/antisynthetase/,'myositis'],[/necrotising myopathy|polymyositis|inclusion body/,'myositis'],[/granulomatosis with polyangiitis|\bgpa\b/,'gpa'],[/eosinophilic granulomatosis|\begpa\b/,'egpa'],[/takayasu/,'takayasu'],[/polyarteritis nodosa|\bpan\b/,'pan'],[/beh[cç]et/,'behcet'],[/cryoglob/,'cryoglob'],[/sarcoid/,'sarcoid'],[/adult-onset still/,'aosd'],[/raynaud/,'raynaud'],[/undifferentiated|ibd-associated|enteropathic/,'earlyia']];for(const [r,k] of map)if(r.test(t))return k;return''}
function likelyFor(title,vig){const t=title.toLowerCase(),v=vig.toLowerCase();const out=[];const add=(cond,s)=>{if(cond&&!out.includes(s))out.push(s)};
 add(/rheumatoid/.test(t)&&/mcp|pip|wrist|symmetr/.test(v),'Small-joint, symmetrical inflammatory pattern is supportive.');
 add(/psoriatic/.test(t)&&/psoriasis|nail|dactyl|enthes/.test(v),'Psoriasis/nail disease, dactylitis or enthesitis supports PsA.');
 add(/spondy|axial/.test(t)&&/night|morning stiffness|improv.*movement|uveitis|enthes/.test(v),'Inflammatory axial features and/or SpA extra-articular clues are supportive.');
 add(/reactive/.test(t)&&/diarr|ureth|infection|weeks|conjunct/.test(v),'A recent GI/GU infection followed by asymmetric inflammatory arthritis supports reactive arthritis.');
 add(/gout/.test(t)&&/abrupt|first mtp|podagra|urate|tophi|hot swollen/.test(v),'Abrupt crystal-pattern monoarthritis and classic distribution/risk factors support gout.');
 add(/cpp|pyrophosphate/.test(t)&&/older|knee|wrist|chondrocalc/.test(v),'Age, knee/wrist pattern and chondrocalcinosis are supportive of CPPD.');
 add(/polymyalgia/.test(t)&&/shoulder|hip|stiffness|older|crp|esr/.test(v),'Age-appropriate proximal girdle stiffness with inflammatory markers supports PMR.');
 add(/giant cell|gca/.test(t)&&/headache|jaw|visual|scalp|temporal/.test(v),'Cranial ischaemic symptoms strongly support GCA and raise urgency.');
 add(/lupus/.test(t)&&/rash|photosens|oral|renal|protein|cytopen|dsdna|complement/.test(v),'Multisystem CTD features and lupus-pattern laboratory findings are supportive.');
 add(/sj[oö]gren/.test(t)&&/dry|sicca|ssa|saliv/.test(v),'Objective sicca/salivary features and compatible serology support Sjögren syndrome.');
 add(/sclerosis|scleroderma/.test(t)&&/raynaud|skin thick|sclerodact|telang|reflux/.test(v),'Raynaud phenomenon plus characteristic skin/vascular features supports systemic sclerosis.');
 add(/myositis|dermatomy|antisynthet|necrotising/.test(t)&&/weakness|ck|rash|mechanic|ild|proximal/.test(v),'Objective proximal weakness, CK elevation and/or disease-specific skin/ILD clues support inflammatory myopathy.');
 add(/vascul|polyangiitis|takayasu|beh|cryoglob|arteritis/.test(t)&&/renal|haematur|lung|purpura|neurop|pulse|aneur|oral ulcer|asthma|eosin/.test(v),'The vignette contains organ-pattern features compatible with systemic vasculitis.');
 add(/fibromyalgia/.test(t)&&/widespread|fatigue|sleep|cognitive/.test(v),'Widespread pain with fatigue/non-restorative sleep supports a nociplastic phenotype.');
 add(/osteoarthritis/.test(t)&&/mechanical|activity|crepitus|bony|brief stiffness/.test(v),'Mechanical pain behaviour and degenerative examination features support OA.');
 if(!out.length&&vig)out.push('The overall symptom pattern and chronology in the initial vignette are compatible with this working diagnosis.');return out.slice(0,4)}
function likelyAgainst(title,vig){const t=title.toLowerCase(),v=vig.toLowerCase(),out=[];const add=(c,s)=>{if(c&&!out.includes(s))out.push(s)};
 add(/polymyalgia/.test(t)&&/\b([1-4][0-9])[- ]?year|aged?\s*[1-4][0-9]/.test(v),'Age under 50 would strongly argue against PMR.');
 add(/polymyalgia/.test(t)&&/knee swelling|swollen knee|synovitis/.test(v),'Prominent peripheral synovitis, especially a swollen knee, should keep inflammatory arthritis high in the differential.');
 add(/fibromyalgia/.test(t)&&/synovitis|swollen joint|ck elevated|proteinuria|haematuria/.test(v),'Objective inflammatory/organ findings are not explained by fibromyalgia alone.');
 add(/osteoarthritis/.test(t)&&/prolonged morning|synovitis|high crp|high esr|systemic/.test(v),'Marked inflammatory features would be atypical for OA as the sole explanation.');
 add(/rheumatoid/.test(t)&&/dactyl|psoriasis|enthes|inflammatory back/.test(v),'SpA/PsA features would argue for a competing seronegative spondyloarthritis phenotype.');
 add(/gout|cpp|pyrophosphate/.test(t)&&/fever|sepsis|immunosupp|prosthetic/.test(v),'Infection remains a major competing diagnosis and must be excluded in a hot swollen joint.');
 if(!out.length)out.push('The initial vignette does not by itself exclude important mimics; competing diagnoses still require active review.');return out.slice(0,4)}

function enhanceSummary(){const root=summaryRoot();if(!root||root.dataset.rdx36==='1')return;root.dataset.rdx36='1';const reviews=[...root.querySelectorAll('.rdx-review')];if(!reviews.length)return;
 reviews.forEach(r=>{const tx=clean(r.textContent).toLowerCase();const bad=/worth reconsidering|you chose:|good reasoning direction|stronger answer|incorrect|retry/.test(tx);r.classList.add('rdx36-review',bad?'bad':'good');const st=document.createElement('div');st.className='rdx36-status '+(bad?'bad':'good');st.innerHTML=bad?'❌ 💡 <span>Review this one</span>':'✅ <span>Correct</span>';r.prepend(st);r.dataset.rdx36wrong=bad?'1':'0'});
 const fb=document.createElement('div');fb.className='rdx36-filterbar';fb.innerHTML='<button type="button" class="active" data-rdx36filter="all">All answers</button><button type="button" data-rdx36filter="wrong">Only answers to review</button>';const first=reviews[0];first.parentElement.insertBefore(fb,first);fb.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;fb.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));const wrong=b.dataset.rdx36filter==='wrong';reviews.forEach(r=>r.classList.toggle('rdx36-hide',wrong&&r.dataset.rdx36wrong!=='1'))});
 const title=currentTitle(),vig=currentVignette(),key=moduleKeyFor(title);const box=document.createElement('div');box.className='rdx36-reason';box.innerHTML='<h3>Why does the initial vignette support this diagnosis?</h3><div class="rdx36-for"><b>FOR</b><ul>'+likelyFor(title,vig).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></div><div class="rdx36-against"><b>AGAINST / UNCERTAINTIES</b><ul>'+likelyAgainst(title,vig).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></div>'+(key?'<button type="button" class="rdx36-modulelink" data-rdx36module="'+esc(key)+'">Open the relevant disease-pattern module →</button>':'');fb.parentElement.insertBefore(box,fb);
 box.querySelector('[data-rdx36module]')?.addEventListener('click',()=>{returnToCase=true;lastSummaryScroll=window.scrollY||0;const k=box.querySelector('[data-rdx36module]').dataset.rdx36module;if(typeof window.openModule==='function')window.openModule(k)});
}
function injectModuleBack(){if(!returnToCase)return;const crit=document.getElementById('criteria');if(!crit||crit.classList.contains('hidden'))return;let b=document.getElementById('rdx36BackToCase');if(!b){b=document.createElement('button');b.id='rdx36BackToCase';b.type='button';b.className='rdx36-backcase';b.textContent='← Back to case review';const anchor=crit.querySelector('.module-nav-intro')||crit.firstElementChild;crit.insertBefore(b,anchor);b.onclick=()=>{returnToCase=false;if(typeof showScreen==='function'){const tab=[...document.querySelectorAll('.tab')].find(x=>/cases/i.test(x.textContent||''));showScreen('cases',tab)}setTimeout(()=>window.scrollTo(0,lastSummaryScroll),80)}}}
let tm;new MutationObserver(()=>{clearTimeout(tm);tm=setTimeout(()=>{enhanceSummary();injectModuleBack()},120)}).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});setTimeout(()=>{enhanceSummary();injectModuleBack()},500);
try{sourceDecks.push(['Case review UX v36','Case summaries now show clear green-tick/red-X+lightbulb status, can filter to incorrect answers only, include a FOR/AGAINST diagnostic-vignette review, and link to the relevant disease module with return navigation to the case.']);renderSources()}catch(e){}
})();